# ==================================================================================================
# This file is generated by Compile.ps1. Do not edit directly.
# Source of truth: scripts/, functions/, config/ and xaml/ in this source tree.
# ==================================================================================================
param(
    [switch] $Mock,
    [switch] $DebugMode,
    [switch] $NoCompileBanner
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Add-Type -AssemblyName PresentationFramework
Add-Type -AssemblyName PresentationCore
Add-Type -AssemblyName WindowsBase
Add-Type -AssemblyName System.Windows.Forms

$sync = [Hashtable]::Synchronized(@{})
$sync.configs = @{}

$sync.App = @{
    Name       = 'Entra Break Glass Configurator'
    Version    = '2.0.0'
    Mock       = [bool] $Mock
    OutputRoot = '.\Output'
}

$sync.State = [Hashtable]::Synchronized(@{
    GraphConnected     = $false
    GraphAccount       = ''
    TenantId           = ''
    TenantDisplayName  = ''
    OnMicrosoftDomain  = ''
    GraphScopes        = @()
    Discovery          = $null
    Plan               = $null
    Result             = $null
    OutputFolder       = ''
    HandoffPath        = ''
    CreatedPasswords   = @()
    Warnings           = @()
    Errors             = @()
    Language           = 'da-DK'
})

$sync.UI = [Hashtable]::Synchronized(@{
    CurrentStep    = 'Velkommen'
    ProcessRunning = $false
    ConfigVisited  = $false
})

$sync.Paths = @{
    Root = if ($PSScriptRoot) { $PSScriptRoot } else { (Get-Location).Path }
}

$sync.App.OutputRoot = Join-Path -Path $sync.Paths.Root -ChildPath 'Output'
New-Item -ItemType Directory -Force -Path $sync.App.OutputRoot | Out-Null

$timestamp = Get-Date -Format 'yyyyMMdd-HHmmss'
$sync.Paths.LogFile = Join-Path -Path $sync.App.OutputRoot -ChildPath "BreakGlassConfigurator_$timestamp.log"

if ($DebugMode) {
    $DebugPreference = 'Continue'
}

function Add-NetIPGroupExclusionToCAPolicies {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][object[]] $Policies,
        [Parameter(Mandatory)][string] $GroupId,
        [Parameter(Mandatory)][bool] $Apply
    )

    $results = @()
    foreach ($policy in $Policies) {
        $policyId = [string](Get-NetIPObjectPropertyValue -InputObject $policy -Name 'id')
        $policyName = [string](Get-NetIPObjectPropertyValue -InputObject $policy -Name 'displayName')
        $conditions = Get-NetIPObjectPropertyValue -InputObject $policy -Name 'conditions'
        $users = Get-NetIPObjectPropertyValue -InputObject $conditions -Name 'users'
        if (-not $users) {
            $users = [pscustomobject]@{}
        }
        $excludeGroups = @(Get-NetIPObjectPropertyValue -InputObject $users -Name 'excludeGroups')
        if ($excludeGroups -contains $GroupId) {
            $results += [pscustomobject]@{ Policy = $policyName; PolicyId = $policyId; Status = 'AlreadyExcluded'; Warning = '' }
            continue
        }
        $updatedUsers = ConvertTo-NetIPPlainHashtable -InputObject $users
        if (-not $updatedUsers) { $updatedUsers = @{} }
        $updatedUsers['excludeGroups'] = @($excludeGroups + $GroupId | Select-Object -Unique)
        $body = @{ conditions = @{ users = $updatedUsers } }
        if (-not $Apply) {
            $results += [pscustomobject]@{ Policy = $policyName; PolicyId = $policyId; Status = 'PlannedPatch'; Warning = '' }
            continue
        }
        if ($sync.App.Mock) {
            $results += [pscustomobject]@{ Policy = $policyName; PolicyId = $policyId; Status = 'Patched'; Warning = '' }
            continue
        }
        try {
            Invoke-NetIPGraphRequest -Method PATCH -Uri "https://graph.microsoft.com/v1.0/identity/conditionalAccess/policies/$policyId" -Body $body | Out-Null
            $results += [pscustomobject]@{ Policy = $policyName; PolicyId = $policyId; Status = 'Patched'; Warning = '' }
        }
        catch {
            $warning = "Conditional Access-politikken '$policyName' kunne ikke opdateres."
            $sync.State.Warnings += $warning
            Write-NetIPLog -Level WARN -Message "$warning $(ConvertTo-NetIPRedactedError -ErrorRecord $_)"
            $results += [pscustomobject]@{ Policy = $policyName; PolicyId = $policyId; Status = 'Failed'; Warning = $warning }
        }
    }
    return $results
}

function Backup-NetIPConditionalAccessPolicies {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][object[]] $Policies,
        [Parameter(Mandatory)][string] $OutputFolder
    )

    return Export-NetIPJsonSafe -InputObject $Policies -Path (Join-Path $OutputFolder 'ca-policies-before.json') -Depth 50
}

function ConvertTo-BreakGlassUpn {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string] $Prefix,
        [Parameter(Mandatory)][string] $OnMicrosoftDomain
    )

    $cleanPrefix = $Prefix.Trim()
    if ([string]::IsNullOrWhiteSpace($cleanPrefix)) { throw 'UPN prefix må ikke være tomt.' }
    if ($cleanPrefix -match '@') { throw 'Angiv kun UPN prefix, ikke et fuldt UPN.' }
    if ($cleanPrefix -notmatch '^[A-Za-z0-9._-]+$') { throw 'UPN prefix må kun indeholde bogstaver, tal, punktum, bindestreg og underscore.' }
    return ('{0}@{1}' -f $cleanPrefix, $OnMicrosoftDomain.ToLowerInvariant())
}

function ConvertTo-NetIPPlainHashtable {
    [CmdletBinding()]
    param([AllowNull()] $InputObject)

    if ($null -eq $InputObject) { return $null }
    if ($InputObject -is [string] -or $InputObject.GetType().IsPrimitive) { return $InputObject }
    if ($InputObject -is [System.Collections.IEnumerable] -and -not ($InputObject -is [System.Collections.IDictionary])) {
        $items = @()
        foreach ($item in $InputObject) { $items += ConvertTo-NetIPPlainHashtable -InputObject $item }
        return $items
    }
    $hash = @{}
    foreach ($property in $InputObject.PSObject.Properties) {
        $hash[$property.Name] = ConvertTo-NetIPPlainHashtable -InputObject $property.Value
    }
    return $hash
}

function ConvertTo-NetIPRedactedError {
    [CmdletBinding()]
    param([AllowNull()] $ErrorRecord)

    $text = if ($null -eq $ErrorRecord) { '' } else { [string] $ErrorRecord }
    $patterns = @(
        '(?i)Authorization:\s*Bearer\s+[A-Za-z0-9\._\-]+',
        '(?i)(access_token|refresh_token|client_secret|password)"?\s*[:=]\s*"[^"]+"',
        'eyJ[A-Za-z0-9_\-]+\.[A-Za-z0-9_\-]+\.[A-Za-z0-9_\-]+'
    )
    foreach ($pattern in $patterns) {
        $text = [regex]::Replace($text, $pattern, '[REDACTED]')
    }
    return $text
}

function Ensure-NetIPGlobalAdministratorAssignment {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)] $User,
        [Parameter(Mandatory)] $RoleDefinition,
        [Parameter(Mandatory)][bool] $Apply
    )

    $userId = [string](Get-NetIPObjectPropertyValue -InputObject $User -Name 'id')
    $upn = [string](Get-NetIPObjectPropertyValue -InputObject $User -Name 'userPrincipalName')
    $roleDefinitionId = [string](Get-NetIPObjectPropertyValue -InputObject $RoleDefinition -Name 'id')
    $roleName = [string](Get-NetIPObjectPropertyValue -InputObject $RoleDefinition -Name 'displayName')

    if ([string]::IsNullOrWhiteSpace($userId) -or [string]::IsNullOrWhiteSpace($roleDefinitionId)) {
        return [pscustomobject]@{
            UserPrincipalName = $upn
            Role = $roleName
            Scope = '/'
            Status = 'Skipped'
            Detail = 'User or role definition missing.'
        }
    }

    if ($sync.App.Mock -or $userId -like 'mock-*') {
        return [pscustomobject]@{
            UserPrincipalName = $upn
            Role = $roleName
            Scope = '/'
            Status = if ($Apply) { 'Assigned' } else { 'Planned' }
            Detail = ''
        }
    }

    $filter = [uri]::EscapeDataString("principalId eq '$userId' and roleDefinitionId eq '$roleDefinitionId' and directoryScopeId eq '/'")
    $existing = @(Get-NetIPGraphCollection -Uri "https://graph.microsoft.com/v1.0/roleManagement/directory/roleAssignments?`$filter=$filter&`$select=id,principalId,roleDefinitionId,directoryScopeId")
    if ($existing.Count -gt 0) {
        return [pscustomobject]@{
            UserPrincipalName = $upn
            Role = $roleName
            Scope = '/'
            Status = 'AlreadyAssigned'
            Detail = ''
        }
    }

    if (-not $Apply) {
        return [pscustomobject]@{
            UserPrincipalName = $upn
            Role = $roleName
            Scope = '/'
            Status = 'Planned'
            Detail = ''
        }
    }

    $body = @{
        principalId = $userId
        roleDefinitionId = $roleDefinitionId
        directoryScopeId = '/'
    }
    Invoke-NetIPGraphRequest -Method POST -Uri 'https://graph.microsoft.com/v1.0/roleManagement/directory/roleAssignments' -Body $body | Out-Null
    return [pscustomobject]@{
        UserPrincipalName = $upn
        Role = $roleName
        Scope = '/'
        Status = 'Assigned'
        Detail = ''
    }
}

function Ensure-NetIPGroupMember {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)] $Group,
        [Parameter(Mandatory)] $User,
        [Parameter(Mandatory)][bool] $Apply
    )

    $groupId = [string](Get-NetIPObjectPropertyValue -InputObject $Group -Name 'id')
    $userId = [string](Get-NetIPObjectPropertyValue -InputObject $User -Name 'id')
    $upn = [string](Get-NetIPObjectPropertyValue -InputObject $User -Name 'userPrincipalName')
    $groupName = [string](Get-NetIPObjectPropertyValue -InputObject $Group -Name 'displayName')
    if ([string]::IsNullOrWhiteSpace($groupId) -or [string]::IsNullOrWhiteSpace($userId)) {
        return [pscustomobject]@{ UserPrincipalName = $upn; Group = $groupName; Status = 'Skipped'; Detail = 'Group or user missing.' }
    }
    if ($sync.App.Mock -or $groupId -like 'planned-*' -or $userId -like 'mock-*') {
        return [pscustomobject]@{ UserPrincipalName = $upn; Group = $groupName; Status = if ($Apply) { 'Added' } else { 'Planned' } }
    }
    $members = Get-NetIPGraphCollection -Uri "https://graph.microsoft.com/v1.0/groups/$groupId/members?`$select=id"
    if (@($members | Where-Object { [string](Get-NetIPObjectPropertyValue -InputObject $_ -Name 'id') -eq $userId }).Count -gt 0) {
        return [pscustomobject]@{ UserPrincipalName = $upn; Group = $groupName; Status = 'AlreadyMember' }
    }
    if (-not $Apply) {
        return [pscustomobject]@{ UserPrincipalName = $upn; Group = $groupName; Status = 'Planned' }
    }
    Invoke-NetIPGraphRequest -Method POST -Uri "https://graph.microsoft.com/v1.0/groups/$groupId/members/`$ref" -Body @{ '@odata.id' = "https://graph.microsoft.com/v1.0/directoryObjects/$userId" } | Out-Null
    return [pscustomobject]@{ UserPrincipalName = $upn; Group = $groupName; Status = 'Added' }
}

function Ensure-NetIPSecurityGroup {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string] $DisplayName,
        [Parameter(Mandatory)][string] $Description,
        [Parameter(Mandatory)][bool] $CreateIfMissing,
        [Parameter(Mandatory)][bool] $Apply
    )

    $group = Get-NetIPGroupByDisplayName -DisplayName $DisplayName
    if ($group) {
        $group | Add-Member -MemberType NoteProperty -Name EnsureStatus -Value 'AlreadyExists' -Force
        $currentDescription = [string](Get-NetIPObjectPropertyValue -InputObject $group -Name 'description')
        if ($currentDescription -ne $Description) {
            if ($Apply) {
                Invoke-NetIPGraphRequest -Method PATCH -Uri "https://graph.microsoft.com/v1.0/groups/$($group.id)" -Body @{ description = $Description } | Out-Null
                $group.description = $Description
                $group.EnsureStatus = 'UpdatedDescription'
            }
            else {
                $group.EnsureStatus = 'PlannedDescriptionUpdate'
            }
        }
        return $group
    }
    if (-not $CreateIfMissing) {
        return [pscustomobject]@{ id = ''; displayName = $DisplayName; EnsureStatus = 'SkippedMissing' }
    }
    if (-not $Apply) {
        return [pscustomobject]@{ id = 'planned-group'; displayName = $DisplayName; description = $Description; EnsureStatus = 'PlannedCreate' }
    }
    $created = New-NetIPSecurityGroup -DisplayName $DisplayName -Description $Description
    $created | Add-Member -MemberType NoteProperty -Name EnsureStatus -Value 'Created' -Force
    return $created
}

function Export-NetIPJsonSafe {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)] $InputObject,
        [Parameter(Mandatory)][string] $Path,
        [int] $Depth = 20
    )

    $folder = Split-Path -Parent $Path
    if ($folder) { New-Item -ItemType Directory -Force -Path $folder | Out-Null }
    $InputObject | ConvertTo-Json -Depth $Depth | Set-Content -LiteralPath $Path -Encoding UTF8
    return $Path
}

function Get-NetIPConditionalAccessPolicies {
    [CmdletBinding()]
    param()

    if ($sync.App.Mock) {
        return @(
            [pscustomobject]@{ id='mock-ca-1'; displayName='CA001 Require MFA'; state='enabled'; conditions=[pscustomobject]@{ users=[pscustomobject]@{ includeUsers=@('All'); excludeGroups=@() } } },
            [pscustomobject]@{ id='mock-ca-2'; displayName='CA002 Block legacy'; state='enabled'; conditions=[pscustomobject]@{ users=[pscustomobject]@{ includeUsers=@('All'); excludeGroups=@('mock-existing') } } },
            [pscustomobject]@{ id='mock-ca-3'; displayName='CA003 Report only'; state='enabledForReportingButNotEnforced'; conditions=[pscustomobject]@{ users=[pscustomobject]@{ includeUsers=@('All'); excludeGroups=@() } } }
        )
    }
    return Get-NetIPGraphCollection -Uri 'https://graph.microsoft.com/v1.0/identity/conditionalAccess/policies'
}

function Get-NetIPConfigFromUI {
    [CmdletBinding()]
    param()

    return $sync.Form.Dispatcher.Invoke([func[hashtable]]{
        @{
            DisplayName1     = $sync.WPFDisplayName1.Text.Trim()
            UserPrefix1      = $sync.WPFUserPrefix1.Text.Trim()
            DisplayName2     = $sync.WPFDisplayName2.Text.Trim()
            UserPrefix2      = $sync.WPFUserPrefix2.Text.Trim()
            GroupName        = $sync.WPFGroupName.Text.Trim()
            GroupDescription = $sync.WPFGroupDescription.Text.Trim()
            CreateUsers      = [bool]$sync.WPFCreateUsers.IsChecked
            CreateGroup      = [bool]$sync.WPFCreateGroup.IsChecked
            AddUsersToGroup  = [bool]$sync.WPFAddUsersToGroup.IsChecked
            PatchCAPolicies  = [bool]$sync.WPFPatchCAPolicies.IsChecked
        }
    })
}

function Get-NetIPGlobalAdministratorRoleDefinition {
    [CmdletBinding()]
    param()

    if ($sync.App.Mock) {
        return [pscustomobject]@{
            id = 'mock-global-admin-role-definition'
            displayName = 'Global Administrator'
        }
    }

    $filter = [uri]::EscapeDataString("displayName eq 'Global Administrator'")
    $roles = @(Get-NetIPGraphCollection -Uri "https://graph.microsoft.com/v1.0/roleManagement/directory/roleDefinitions?`$filter=$filter&`$select=id,displayName")
    $role = $roles | Select-Object -First 1
    if (-not $role) {
        throw 'Kunne ikke finde role definition for Global Administrator via Microsoft Graph.'
    }
    return $role
}

function Get-NetIPGraphCollection {
    [CmdletBinding()]
    param([Parameter(Mandatory)][string] $Uri)

    $items = @()
    $next = $Uri
    while ($next) {
        $response = Invoke-NetIPGraphRequest -Method GET -Uri $next
        $value = Get-NetIPObjectPropertyValue -InputObject $response -Name 'value'
        if ($value) { $items += @($value) }
        $next = Get-NetIPObjectPropertyValue -InputObject $response -Name '@odata.nextLink'
    }
    return $items
}

function Get-NetIPGroupByDisplayName {
    [CmdletBinding()]
    param([Parameter(Mandatory)][string] $DisplayName)

    if ($sync.App.Mock) {
        if ($DisplayName -eq 'CA-BreakGlass-Exclude') {
            return $null
        }
        return $null
    }
    $filter = [uri]::EscapeDataString("displayName eq '$($DisplayName.Replace("'", "''"))'")
    return Get-NetIPGraphCollection -Uri "https://graph.microsoft.com/v1.0/groups?`$filter=$filter&`$select=id,displayName,description,mailNickname,securityEnabled,mailEnabled,groupTypes" | Select-Object -First 1
}

function Get-NetIPObjectPropertyValue {
    [CmdletBinding()]
    param(
        [AllowNull()] $InputObject,
        [Parameter(Mandatory)][string] $Name
    )

    if ($null -eq $InputObject) { return $null }
    if ($InputObject -is [System.Collections.IDictionary]) {
        if ($InputObject.Contains($Name)) {
            return $InputObject[$Name]
        }
        foreach ($key in $InputObject.Keys) {
            if ([string]::Equals([string]$key, $Name, [System.StringComparison]::OrdinalIgnoreCase)) {
                return $InputObject[$key]
            }
        }
        return $null
    }
    $property = $InputObject.PSObject.Properties | Where-Object { [string]::Equals($_.Name, $Name, [System.StringComparison]::OrdinalIgnoreCase) } | Select-Object -First 1
    if ($property) { return $property.Value }
    return $null
}

function Get-NetIPOnMicrosoftDomain {
    [CmdletBinding()]
    param([Parameter(Mandatory)] $Organization)

    $domains = @(Get-NetIPObjectPropertyValue -InputObject $Organization -Name 'verifiedDomains')
    $default = $domains | Where-Object { $_.isDefault -eq $true -and $_.name -like '*.onmicrosoft.com' } | Select-Object -First 1
    if ($default) { return [string] $default.name }
    $any = $domains | Where-Object { $_.name -like '*.onmicrosoft.com' } | Select-Object -First 1
    if ($any) { return [string] $any.name }
    throw 'Kunne ikke finde tenantens .onmicrosoft.com domæne.'
}

function Get-NetIPTenantInfo {
    [CmdletBinding()]
    param()

    if ($sync.App.Mock) {
        $info = [pscustomobject]@{
            TenantId          = '00000000-0000-0000-0000-000000000001'
            TenantDisplayName = 'Contoso Demo Tenant'
            OnMicrosoftDomain = 'contoso.onmicrosoft.com'
        }
        $sync.State.TenantId = $info.TenantId
        $sync.State.TenantDisplayName = $info.TenantDisplayName
        $sync.State.OnMicrosoftDomain = $info.OnMicrosoftDomain
        return $info
    }

    $org = Get-NetIPGraphCollection -Uri 'https://graph.microsoft.com/v1.0/organization?$select=id,displayName,verifiedDomains' | Select-Object -First 1
    if (-not $org) { throw 'Kunne ikke læse tenant information fra Microsoft Graph.' }
    $info = [pscustomobject]@{
        TenantId          = [string](Get-NetIPObjectPropertyValue -InputObject $org -Name 'id')
        TenantDisplayName = [string](Get-NetIPObjectPropertyValue -InputObject $org -Name 'displayName')
        OnMicrosoftDomain = Get-NetIPOnMicrosoftDomain -Organization $org
    }
    $sync.State.TenantId = $info.TenantId
    $sync.State.TenantDisplayName = $info.TenantDisplayName
    $sync.State.OnMicrosoftDomain = $info.OnMicrosoftDomain
    return $info
}

function Get-NetIPUserByUpn {
    [CmdletBinding()]
    param([Parameter(Mandatory)][string] $UserPrincipalName)

    if ($sync.App.Mock) {
        if ($UserPrincipalName -like 'BreakGlass01@*') {
            return [pscustomobject]@{ id = 'mock-user-1'; displayName = 'BreakGlass 01'; userPrincipalName = $UserPrincipalName; accountEnabled = $true }
        }
        return $null
    }
    try {
        return Invoke-NetIPGraphRequest -Method GET -Uri ("https://graph.microsoft.com/v1.0/users/{0}?`$select=id,displayName,userPrincipalName,accountEnabled" -f [uri]::EscapeDataString($UserPrincipalName)) -SuppressNotFoundLog
    }
    catch {
        if ([string]$_ -match '404|Request_ResourceNotFound|Resource .* does not exist') { return $null }
        throw
    }
}

function Invoke-NetIPGraphRequest {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][ValidateSet('GET','POST','PATCH','DELETE')][string] $Method,
        [Parameter(Mandatory)][string] $Uri,
        [AllowNull()] $Body = $null,
        [switch] $SuppressNotFoundLog
    )

    if ($sync.App.Mock) {
        throw 'Mock mode should not call Microsoft Graph.'
    }
    $params = @{
        Method      = $Method
        Uri         = $Uri
        ErrorAction = 'Stop'
    }
    if ($null -ne $Body) {
        $params.Body = if ($Body -is [string]) { $Body } else { ($Body | ConvertTo-Json -Depth 30) }
        $params.ContentType = 'application/json'
    }
    try {
        return Invoke-MgGraphRequest @params
    }
    catch {
        $message = [string]$_
        $isNotFound = $message -match '404|Request_ResourceNotFound|Resource .* does not exist'
        if (-not ($SuppressNotFoundLog -and $isNotFound)) {
            Write-NetIPLog -Level ERROR -Message (ConvertTo-NetIPRedactedError -ErrorRecord $_)
        }
        throw
    }
}

function Invoke-NetIPRunspace {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][scriptblock] $ScriptBlock,
        [object[]] $ArgumentList = @()
    )

    if ($sync.UI.ProcessRunning) {
        [System.Windows.MessageBox]::Show('Der kører allerede en opgave. Vent til den er færdig.', $sync.App.Name, 'OK', 'Information') | Out-Null
        return
    }
    $sync.UI.ProcessRunning = $true
    if ($sync.WPFProgressBar) {
        $sync.WPFProgressBar.Dispatcher.Invoke([System.Action]{ $sync.WPFProgressBar.IsIndeterminate = $true })
    }
    $ps = [PowerShell]::Create()
    $ps.RunspacePool = $sync.Runspace
    [void]$ps.AddScript({
        param($innerScript, $innerArgs)
        try {
            & $innerScript @innerArgs
        }
        catch {
            $friendly = 'Der opstod en fejl. Se logfilen for tekniske detaljer.'
            Write-NetIPLog -Level ERROR -Message (ConvertTo-NetIPRedactedError -ErrorRecord $_)
            $sync.State.Errors += $friendly
            if ($sync.Form) {
                $sync.Form.Dispatcher.Invoke([System.Action]{
                    $sync.WPFStatusText.Text = $friendly
                    [System.Windows.MessageBox]::Show($friendly, $sync.App.Name, 'OK', 'Error') | Out-Null
                })
            }
        }
        finally {
            $sync.UI.ProcessRunning = $false
            if ($sync.Form) {
                $sync.Form.Dispatcher.Invoke([System.Action]{
                    $sync.WPFProgressBar.IsIndeterminate = $false
                    Update-NetIPUIState
                })
            }
        }
    }).AddArgument($ScriptBlock).AddArgument($ArgumentList) | Out-Null
    [void]$ps.BeginInvoke()
}

function New-BreakGlassUser {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string] $DisplayName,
        [Parameter(Mandatory)][string] $UserPrincipalName,
        [Parameter(Mandatory)][string] $Password
    )

    if ($sync.App.Mock) {
        return [pscustomobject]@{ id = "mock-$($UserPrincipalName.Split('@')[0])"; displayName = $DisplayName; userPrincipalName = $UserPrincipalName; accountEnabled = $true; EnsureStatus = 'Created' }
    }
    $mailNickname = ($UserPrincipalName.Split('@')[0] -replace '[^A-Za-z0-9]', '')
    $body = @{
        accountEnabled    = $true
        displayName       = $DisplayName
        mailNickname      = $mailNickname
        userPrincipalName = $UserPrincipalName
        passwordProfile   = @{
            forceChangePasswordNextSignIn = $false
            password = $Password
        }
    }
    Invoke-NetIPGraphRequest -Method POST -Uri 'https://graph.microsoft.com/v1.0/users' -Body $body | Out-Null
    $user = Get-NetIPUserByUpn -UserPrincipalName $UserPrincipalName
    $user | Add-Member -MemberType NoteProperty -Name EnsureStatus -Value 'Created' -Force
    return $user
}

function New-NetIPHandoffHtml {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)] $Result,
        [Parameter(Mandatory)][string] $OutputFolder
    )

    function ConvertTo-NetIPHtmlValue([AllowNull()]$value) { [System.Net.WebUtility]::HtmlEncode([string]$value) }
    function Get-NetIPTablePropertyNames([AllowNull()]$item) {
        if ($null -eq $item) { return @() }
        if ($item -is [System.Collections.IDictionary]) {
            return @($item.Keys | ForEach-Object { [string]$_ })
        }
        return @($item.PSObject.Properties.Name)
    }
    function Rows($items) {
        if (-not $items -or @($items).Count -eq 0) { return '<p>Ingen.</p>' }
        $props = @($items | ForEach-Object { Get-NetIPTablePropertyNames $_ } | Select-Object -Unique)
        $head = '<tr>' + (($props | ForEach-Object { '<th>{0}</th>' -f (ConvertTo-NetIPHtmlValue $_) }) -join '') + '</tr>'
        $body = foreach ($item in $items) {
            '<tr>' + (($props | ForEach-Object { '<td>{0}</td>' -f (ConvertTo-NetIPHtmlValue (Get-NetIPObjectPropertyValue -InputObject $item -Name $_)) }) -join '') + '</tr>'
        }
        return '<table>' + $head + ($body -join "`n") + '</table>'
    }

    $path = Join-Path $OutputFolder 'handoff.html'
    New-Item -ItemType Directory -Force -Path $OutputFolder | Out-Null
    $account1 = Get-NetIPObjectPropertyValue -InputObject $Result -Name 'Account1'
    $account2 = Get-NetIPObjectPropertyValue -InputObject $Result -Name 'Account2'
    $group = Get-NetIPObjectPropertyValue -InputObject $Result -Name 'Group'
    $changed = @(Get-NetIPObjectPropertyValue -InputObject $Result -Name 'CAPoliciesChanged')
    $already = @(Get-NetIPObjectPropertyValue -InputObject $Result -Name 'CAPoliciesAlreadyExcluded')
    $failed = @(Get-NetIPObjectPropertyValue -InputObject $Result -Name 'CAPoliciesFailed')
    $memberships = @(Get-NetIPObjectPropertyValue -InputObject $Result -Name 'GroupMembership')
    $roleAssignments = @(Get-NetIPObjectPropertyValue -InputObject $Result -Name 'RoleAssignments')
    $resultWarnings = @(Get-NetIPObjectPropertyValue -InputObject $Result -Name 'Warnings')
    $changedTable = Rows $changed
    $alreadyTable = Rows $already
    $failedTable = Rows $failed
    $membershipTable = Rows $memberships
    $roleAssignmentTable = Rows $roleAssignments
    $warnings = if ($resultWarnings.Count -gt 0) { '<ul>' + (($resultWarnings | ForEach-Object { '<li>{0}</li>' -f (ConvertTo-NetIPHtmlValue $_) }) -join '') + '</ul>' } else { '<p>Ingen.</p>' }
    $html = @"
<!doctype html>
<html lang="da">
<head>
  <meta charset="utf-8">
  <title>CONFIDENTIAL - Break Glass Handoff</title>
  <style>
    body { font-family: Segoe UI, Arial, sans-serif; margin: 32px; color: #111827; line-height: 1.45; }
    .banner { background:#7f1d1d; color:white; padding:14px 18px; font-weight:700; font-size:22px; }
    table { border-collapse: collapse; width: 100%; margin: 10px 0 18px 0; }
    th, td { border: 1px solid #d1d5db; padding: 8px 10px; text-align: left; vertical-align: top; }
    th { background: #f3f4f6; }
    h2 { border-bottom: 1px solid #d1d5db; padding-bottom: 6px; margin-top: 28px; }
  </style>
</head>
<body>
  <div class="banner">CONFIDENTIAL - HANDOFF</div>
  <h1>Entra Break Glass handoff</h1>
  <p>Dette dokument indeholder ikke adgangskoder, tokens eller secrets.</p>
  <h2>Tenant</h2>
  <table>
    <tr><th>Tenant navn</th><td>$(ConvertTo-NetIPHtmlValue (Get-NetIPObjectPropertyValue -InputObject $Result -Name 'TenantDisplayName'))</td></tr>
    <tr><th>Tenant ID</th><td>$(ConvertTo-NetIPHtmlValue (Get-NetIPObjectPropertyValue -InputObject $Result -Name 'TenantId'))</td></tr>
    <tr><th>Dato/tid</th><td>$(ConvertTo-NetIPHtmlValue (Get-NetIPObjectPropertyValue -InputObject $Result -Name 'Timestamp'))</td></tr>
    <tr><th>Konsulent / Graph konto</th><td>$(ConvertTo-NetIPHtmlValue (Get-NetIPObjectPropertyValue -InputObject $Result -Name 'Operator'))</td></tr>
    <tr><th>.onmicrosoft.com domæne</th><td>$(ConvertTo-NetIPHtmlValue (Get-NetIPObjectPropertyValue -InputObject $Result -Name 'OnMicrosoftDomain'))</td></tr>
  </table>
  <h2>Break-glass konti</h2>
  <table>
    <tr><th>Konto 1 display name</th><td>$(ConvertTo-NetIPHtmlValue (Get-NetIPObjectPropertyValue -InputObject $account1 -Name 'DisplayName'))</td></tr>
    <tr><th>Konto 1 UPN</th><td>$(ConvertTo-NetIPHtmlValue (Get-NetIPObjectPropertyValue -InputObject $account1 -Name 'UserPrincipalName'))</td></tr>
    <tr><th>Konto 1 status</th><td>$(ConvertTo-NetIPHtmlValue (Get-NetIPObjectPropertyValue -InputObject $account1 -Name 'Status'))</td></tr>
    <tr><th>Konto 2 display name</th><td>$(ConvertTo-NetIPHtmlValue (Get-NetIPObjectPropertyValue -InputObject $account2 -Name 'DisplayName'))</td></tr>
    <tr><th>Konto 2 UPN</th><td>$(ConvertTo-NetIPHtmlValue (Get-NetIPObjectPropertyValue -InputObject $account2 -Name 'UserPrincipalName'))</td></tr>
    <tr><th>Konto 2 status</th><td>$(ConvertTo-NetIPHtmlValue (Get-NetIPObjectPropertyValue -InputObject $account2 -Name 'Status'))</td></tr>
  </table>
  <h2>Security group</h2>
  <table>
    <tr><th>Navn</th><td>$(ConvertTo-NetIPHtmlValue (Get-NetIPObjectPropertyValue -InputObject $group -Name 'DisplayName'))</td></tr>
    <tr><th>Object ID</th><td>$(ConvertTo-NetIPHtmlValue (Get-NetIPObjectPropertyValue -InputObject $group -Name 'Id'))</td></tr>
    <tr><th>Status</th><td>$(ConvertTo-NetIPHtmlValue (Get-NetIPObjectPropertyValue -InputObject $group -Name 'Status'))</td></tr>
  </table>
  <h2>Gruppemedlemskab</h2>
  $membershipTable
  <h2>Administratorrolle</h2>
  <p>Begge break-glass konti tildeles direkte Global Administrator på tenant scope (/).</p>
  $roleAssignmentTable
  <h2>Conditional Access</h2>
  <table>
    <tr><th>CA exclusions valgt</th><td>$(ConvertTo-NetIPHtmlValue (Get-NetIPObjectPropertyValue -InputObject $Result -Name 'CAExclusionsEnabled'))</td></tr>
    <tr><th>Antal policies ændret</th><td>$(ConvertTo-NetIPHtmlValue (Get-NetIPObjectPropertyValue -InputObject $Result -Name 'CAPoliciesChangedCount'))</td></tr>
    <tr><th>Backup path</th><td>$(ConvertTo-NetIPHtmlValue (Get-NetIPObjectPropertyValue -InputObject $Result -Name 'CABackupPath'))</td></tr>
  </table>
  <h3>Policies ændret</h3>
  $changedTable
  <h3>Policies der allerede ekskluderede gruppen</h3>
  $alreadyTable
  <h3>Policies der fejlede</h3>
  $failedTable
  <h2>Advarsler/fejl</h2>
  $warnings
  <h2>Manuelle næste steps</h2>
  <ol>
    <li>Gem de genererede adgangskoder sikkert efter intern/kundeprocedure.</li>
    <li>Konfigurer MFA/FIDO2/passkey manuelt, hvis det indgår i kundens standard.</li>
    <li>Verificér at begge break-glass konti har direkte Global Administrator rolle.</li>
    <li>Verificér at begge break-glass konti kan logge ind.</li>
    <li>Verificér at kontiene er medlem af CA-BreakGlass-Exclude.</li>
    <li>Verificér at gruppen er ekskluderet fra de ønskede Conditional Access-politikker, hvis funktionen blev valgt.</li>
    <li>Dokumentér hvor credentials opbevares.</li>
    <li>Aftal periodisk test/review med kunden.</li>
  </ol>
</body>
</html>
"@
    Set-Content -LiteralPath $path -Value $html -Encoding UTF8
    $sync.State.HandoffPath = $path
    return $path
}

function New-NetIPOutputFolder {
    [CmdletBinding()]
    param([Parameter(Mandatory)][string] $TenantId)

    $safeTenant = if ([string]::IsNullOrWhiteSpace($TenantId)) { 'UnknownTenant' } else { $TenantId }
    $folder = Join-Path -Path $sync.App.OutputRoot -ChildPath ('BreakGlass-{0}-{1}' -f $safeTenant, (Get-Date -Format 'yyyyMMdd-HHmmss'))
    New-Item -ItemType Directory -Force -Path $folder | Out-Null
    $sync.State.OutputFolder = $folder
    return $folder
}

function New-NetIPPlanObject {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][hashtable] $Config,
        [AllowNull()] $Discovery = $null
    )

    $tenant = Get-NetIPTenantInfo
    $upn1 = ConvertTo-BreakGlassUpn -Prefix $Config.UserPrefix1 -OnMicrosoftDomain $tenant.OnMicrosoftDomain
    $upn2 = ConvertTo-BreakGlassUpn -Prefix $Config.UserPrefix2 -OnMicrosoftDomain $tenant.OnMicrosoftDomain
    $user1 = if ($Discovery) { $Discovery.User1 } else { Get-NetIPUserByUpn -UserPrincipalName $upn1 }
    $user2 = if ($Discovery) { $Discovery.User2 } else { Get-NetIPUserByUpn -UserPrincipalName $upn2 }
    $group = if ($Discovery) { $Discovery.Group } else { Get-NetIPGroupByDisplayName -DisplayName $Config.GroupName }
    $policies = if ($Discovery) { @($Discovery.CAPolicies) } else { @(Get-NetIPConditionalAccessPolicies) }

    $alreadyExcluded = @()
    $toPatch = @()
    if ($group -and $group.id) {
        foreach ($policy in $policies) {
            $excludeGroups = @(Get-NetIPObjectPropertyValue -InputObject (Get-NetIPObjectPropertyValue -InputObject (Get-NetIPObjectPropertyValue -InputObject $policy -Name 'conditions') -Name 'users') -Name 'excludeGroups')
            if ($excludeGroups -contains $group.id) { $alreadyExcluded += $policy }
            elseif ($Config.PatchCAPolicies) { $toPatch += $policy }
        }
    }
    elseif ($Config.PatchCAPolicies) {
        $toPatch = @($policies)
    }

    $warnings = @()
    if ($user1) { $warnings += 'Konto 1 findes allerede. Password bliver ikke ændret automatisk.' }
    if ($user2) { $warnings += 'Konto 2 findes allerede. Password bliver ikke ændret automatisk.' }
    $warnings += 'Begge break-glass konti får direkte Global Administrator rolle på tenant scope (/).'
    if ($Config.PatchCAPolicies) { $warnings += 'Eksisterende Conditional Access-politikker ændres. Backup oprettes før ændringer.' }

    $outputFolder = if ($sync.State.OutputFolder) { $sync.State.OutputFolder } else { Join-Path $sync.App.OutputRoot ('BreakGlass-{0}-<timestamp>' -f $tenant.TenantId) }
    $plan = [pscustomobject]@{
        TenantId                  = $tenant.TenantId
        TenantDisplayName         = $tenant.TenantDisplayName
        OnMicrosoftDomain         = $tenant.OnMicrosoftDomain
        Account1DisplayName       = $Config.DisplayName1
        Account1UPN               = $upn1
        Account1Status            = if ($user1) { 'Eksisterer allerede' } elseif ($Config.CreateUsers) { 'Oprettes' } else { 'Springes over' }
        Account2DisplayName       = $Config.DisplayName2
        Account2UPN               = $upn2
        Account2Status            = if ($user2) { 'Eksisterer allerede' } elseif ($Config.CreateUsers) { 'Oprettes' } else { 'Springes over' }
        GroupName                 = $Config.GroupName
        GroupStatus               = if ($group) { 'Eksisterer allerede' } elseif ($Config.CreateGroup) { 'Oprettes' } else { 'Springes over' }
        AddAccountsToGroup        = [bool]$Config.AddUsersToGroup
        AssignGlobalAdministrator = $true
        RoleAssignmentScope       = '/'
        ConditionalAccessCount    = @($policies).Count
        PatchConditionalAccess    = [bool]$Config.PatchCAPolicies
        CAPoliciesToChange        = @($toPatch | Select-Object id,displayName,state)
        CAPoliciesAlreadyExcluded = @($alreadyExcluded | Select-Object id,displayName,state)
        OutputFolder              = $outputFolder
        HandoffPath               = Join-Path $outputFolder 'handoff.html'
        Warnings                  = $warnings
        GeneratedAt               = (Get-Date).ToString('o')
    }
    $sync.State.Plan = $plan
    return $plan
}

function New-NetIPRandomPassword {
    [CmdletBinding()]
    param([int] $Length = 28)

    if ($Length -lt 24) { $Length = 24 }
    $upper = 'ABCDEFGHJKLMNPQRSTUVWXYZ'
    $lower = 'abcdefghijkmnopqrstuvwxyz'
    $digits = '23456789'
    $symbols = '!#$%&*+-=?@_'
    $all = ($upper + $lower + $digits + $symbols).ToCharArray()
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    function Get-RandomChar([char[]] $Chars) {
        $bytes = [byte[]]::new(4)
        $rng.GetBytes($bytes)
        return $Chars[[BitConverter]::ToUInt32($bytes, 0) % $Chars.Count]
    }
    $chars = @(
        (Get-RandomChar $upper.ToCharArray()),
        (Get-RandomChar $lower.ToCharArray()),
        (Get-RandomChar $digits.ToCharArray()),
        (Get-RandomChar $symbols.ToCharArray())
    )
    while ($chars.Count -lt $Length) { $chars += Get-RandomChar $all }
    $shuffled = $chars | Sort-Object { Get-Random }
    return -join $shuffled
}

function New-NetIPSecurityGroup {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string] $DisplayName,
        [Parameter(Mandatory)][string] $Description
    )

    if ($sync.App.Mock) {
        return [pscustomobject]@{ id = 'mock-ca-exclude-group'; displayName = $DisplayName; description = $Description; mailEnabled = $false; securityEnabled = $true; groupTypes = @(); EnsureStatus = 'Created' }
    }
    $body = @{
        displayName     = $DisplayName
        description     = $Description
        mailEnabled     = $false
        mailNickname    = 'CABreakGlassExclude'
        securityEnabled = $true
        groupTypes      = @()
    }
    Invoke-NetIPGraphRequest -Method POST -Uri 'https://graph.microsoft.com/v1.0/groups' -Body $body | Out-Null
    return Get-NetIPGroupByDisplayName -DisplayName $DisplayName
}

function Save-NetIPResultJson {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)] $Result,
        [Parameter(Mandatory)][string] $OutputFolder
    )

    return Export-NetIPJsonSafe -InputObject $Result -Path (Join-Path $OutputFolder 'result.json') -Depth 40
}

function Set-NetIPLanguage {
    [CmdletBinding()]
    param([ValidateSet('da-DK','en-US')][string] $Language = 'da-DK')

    if (-not $sync.Form) { return }
    if (-not $sync.Form.Dispatcher.CheckAccess()) {
        $sync.Form.Dispatcher.Invoke([System.Action]{ Set-NetIPLanguage -Language $Language })
        return
    }

    $sync.State.Language = $Language
    $strings = @(
        @{ Da = 'Entra Break Glass Configurator'; En = 'Entra Break Glass Configurator' }
        @{ Da = 'Simpel Microsoft Graph-baseret opsætning af break-glass konti og CA-exclude gruppe.'; En = 'Simple Microsoft Graph-based setup of break-glass accounts and a CA exclude group.' }
        @{ Da = '1. Velkommen'; En = '1. Welcome' }
        @{ Da = '2. Forbind'; En = '2. Connect' }
        @{ Da = '3. Discovery'; En = '3. Discovery' }
        @{ Da = '4. Konfiguration'; En = '4. Configuration' }
        @{ Da = '5. Plan'; En = '5. Plan' }
        @{ Da = '6. Udfør'; En = '6. Apply' }
        @{ Da = '7. Handoff'; En = '7. Handoff' }
        @{ Da = 'Sprog'; En = 'Language' }
        @{ Da = 'Velkommen'; En = 'Welcome' }
        @{ Da = 'Dette værktøj opretter to break-glass konti på tenantens .onmicrosoft.com domæne, opretter gruppen CA-BreakGlass-Exclude og kan valgfrit ekskludere gruppen fra eksisterende Conditional Access-politikker.'; En = 'This tool creates two break-glass accounts on the tenant .onmicrosoft.com domain, creates the CA-BreakGlass-Exclude group, and can optionally exclude the group from existing Conditional Access policies.' }
        @{ Da = 'Værktøjet forbinder kun til Microsoft Graph. Det bruger ikke Azure, PIM, RMAU, FIDO2, Log Analytics eller Sentinel.'; En = 'The tool connects only to Microsoft Graph. It does not use Azure, PIM, RMAU, FIDO2, Log Analytics, or Sentinel.' }
        @{ Da = 'Discovery og Plan foretager ingen ændringer. Ændringer udføres først i trinnet Udfør.'; En = 'Discovery and Plan make no changes. Changes are performed only in the Apply step.' }
        @{ Da = 'Midlertidige adgangskoder vises kun én gang og gemmes ikke i log, JSON eller handoff dokument.'; En = 'Temporary passwords are shown only once and are not saved to logs, JSON, or the handoff document.' }
        @{ Da = 'Jeg forstår at dette script ændrer sikkerhedskritisk tenant-konfiguration.'; En = 'I understand that this script changes security-critical tenant configuration.' }
        @{ Da = 'Forbind'; En = 'Connect' }
        @{ Da = 'Forbind én gang til Microsoft Graph. Samme session bruges til discovery, plan og udførsel.'; En = 'Connect once to Microsoft Graph. The same session is used for discovery, plan, and apply.' }
        @{ Da = 'Requested Graph scopes:'; En = 'Requested Graph scopes:' }
        @{ Da = 'Forbind til Microsoft 365 tenant'; En = 'Connect to Microsoft 365 tenant' }
        @{ Da = 'Forbundet:'; En = 'Connected:' }
        @{ Da = 'Konto:'; En = 'Account:' }
        @{ Da = 'Tenant navn:'; En = 'Tenant name:' }
        @{ Da = '.onmicrosoft.com domæne:'; En = '.onmicrosoft.com domain:' }
        @{ Da = 'Nej'; En = 'No' }
        @{ Da = 'Ja'; En = 'Yes' }
        @{ Da = 'Discovery er read-only og kontrollerer kun de eksakte target UPNs, CA-BreakGlass-Exclude og eksisterende Conditional Access-politikker.'; En = 'Discovery is read-only and checks only the exact target UPNs, CA-BreakGlass-Exclude, and existing Conditional Access policies.' }
        @{ Da = 'Kør discovery'; En = 'Run discovery' }
        @{ Da = 'Konfiguration'; En = 'Configuration' }
        @{ Da = 'Account 1 display name'; En = 'Account 1 display name' }
        @{ Da = 'Account 1 UPN prefix'; En = 'Account 1 UPN prefix' }
        @{ Da = 'Account 2 display name'; En = 'Account 2 display name' }
        @{ Da = 'Account 2 UPN prefix'; En = 'Account 2 UPN prefix' }
        @{ Da = 'Domain'; En = 'Domain' }
        @{ Da = 'Final UPN preview'; En = 'Final UPN preview' }
        @{ Da = 'Security group name'; En = 'Security group name' }
        @{ Da = 'Security group description'; En = 'Security group description' }
        @{ Da = 'Opret brugere hvis de ikke findes'; En = 'Create users if missing' }
        @{ Da = 'Opret gruppen CA-BreakGlass-Exclude hvis den ikke findes'; En = 'Create CA-BreakGlass-Exclude if missing' }
        @{ Da = 'Tilføj break-glass konti til CA-BreakGlass-Exclude'; En = 'Add break-glass accounts to CA-BreakGlass-Exclude' }
        @{ Da = 'Ekskludér CA-BreakGlass-Exclude fra alle eksisterende Conditional Access-politikker'; En = 'Exclude CA-BreakGlass-Exclude from all existing Conditional Access policies' }
        @{ Da = 'Dette ændrer eksisterende Conditional Access-politikker. Der oprettes backup før ændringerne udføres.'; En = 'This changes existing Conditional Access policies. A backup is created before changes are applied.' }
        @{ Da = 'Generér plan'; En = 'Generate plan' }
        @{ Da = 'Udfør'; En = 'Apply' }
        @{ Da = 'Dette er det eneste trin der ændrer tenant-konfiguration.'; En = 'This is the only step that changes tenant configuration.' }
        @{ Da = 'Anvend konfiguration'; En = 'Apply configuration' }
        @{ Da = 'Handoff-dokumentet genereres efter udførsel. Det indeholder ikke passwords.'; En = 'The handoff document is generated after apply. It does not contain passwords.' }
        @{ Da = 'Output folder'; En = 'Output folder' }
        @{ Da = 'Handoff dokument'; En = 'Handoff document' }
        @{ Da = 'Åbn outputmappe'; En = 'Open output folder' }
        @{ Da = 'Åbn handoff'; En = 'Open handoff' }
        @{ Da = 'Klar'; En = 'Ready' }
    )

    function Convert-AppText([AllowNull()][string] $Text) {
        if ([string]::IsNullOrWhiteSpace($Text)) { return $Text }
        foreach ($entry in $strings) {
            if ($Text -eq $entry.Da -or $Text -eq $entry.En) {
                if ($Language -eq 'en-US') { return $entry.En }
                return $entry.Da
            }
        }
        return $Text
    }

    function Update-TextObject([AllowNull()] $Object) {
        if ($null -eq $Object) { return }
        if ($Object -is [System.Windows.Controls.ComboBoxItem]) { return }
        if ($Object -is [System.Windows.Controls.TextBlock]) {
            $Object.Text = Convert-AppText $Object.Text
        }
        elseif ($Object -is [System.Windows.Controls.Button] -or $Object -is [System.Windows.Controls.CheckBox]) {
            if ($Object.Content -is [string]) { $Object.Content = Convert-AppText ([string]$Object.Content) }
        }
        elseif ($Object -is [System.Windows.Controls.TextBox]) {
            if (-not $Object.AcceptsReturn -and $Object.IsReadOnly -and -not [string]::IsNullOrWhiteSpace($Object.Text)) {
                $Object.Text = Convert-AppText $Object.Text
            }
        }
        if (-not ($Object -is [System.Windows.DependencyObject])) { return }
        foreach ($child in [System.Windows.LogicalTreeHelper]::GetChildren($Object)) {
            Update-TextObject $child
        }
    }

    $sync.Form.Title = "$($sync.App.Name) v$($sync.App.Version)"
    Update-TextObject $sync.Form
    if ($sync.WPFAppTitle) { $sync.WPFAppTitle.Text = $sync.App.Name }
    if ($sync.WPFVersionBadge) { $sync.WPFVersionBadge.Text = "v$($sync.App.Version)" }
}

function Show-NetIPCreatedPasswordsOnce {
    [CmdletBinding()]
    param([object[]] $CreatedPasswords)

    if (-not $CreatedPasswords -or $CreatedPasswords.Count -eq 0) { return }
    $sync.Form.Dispatcher.Invoke([System.Action]{
        $window = New-Object System.Windows.Window
        $window.Title = 'Midlertidige adgangskoder - vises kun én gang'
        $window.Width = 720
        $window.Height = 430
        $window.WindowStartupLocation = 'CenterOwner'
        $window.Owner = $sync.Form
        $window.Topmost = $true
        $panel = New-Object System.Windows.Controls.DockPanel
        $panel.Margin = '16'
        $warning = New-Object System.Windows.Controls.TextBlock
        $warning.Text = 'Adgangskoderne vises kun her. De skrives ikke til log, JSON eller handoff. Gem dem straks sikkert efter intern/kundeprocedure.'
        $warning.TextWrapping = 'Wrap'
        $warning.Margin = '0,0,0,10'
        [System.Windows.Controls.DockPanel]::SetDock($warning, 'Top')
        $panel.Children.Add($warning) | Out-Null
        $text = New-Object System.Windows.Controls.TextBox
        $text.IsReadOnly = $true
        $text.AcceptsReturn = $true
        $text.VerticalScrollBarVisibility = 'Auto'
        $text.FontFamily = 'Consolas'
        $text.Text = (($CreatedPasswords | ForEach-Object {
            '{0}: {1}' -f (Get-NetIPObjectPropertyValue -InputObject $_ -Name 'UserPrincipalName'), (Get-NetIPObjectPropertyValue -InputObject $_ -Name 'Password')
        }) -join [Environment]::NewLine)
        $panel.Children.Add($text) | Out-Null
        $buttons = New-Object System.Windows.Controls.StackPanel
        $buttons.Orientation = 'Horizontal'
        $buttons.HorizontalAlignment = 'Right'
        $buttons.Margin = '0,10,0,0'
        [System.Windows.Controls.DockPanel]::SetDock($buttons, 'Bottom')
        $copy = New-Object System.Windows.Controls.Button
        $copy.Content = 'Kopiér alle'
        $copy.Width = 110
        $copy.Margin = '0,0,8,0'
        $copy.Add_Click({ [System.Windows.Clipboard]::SetText($text.Text) })
        $close = New-Object System.Windows.Controls.Button
        $close.Content = 'Luk'
        $close.Width = 90
        $close.Add_Click({ $window.Close() })
        $buttons.Children.Add($copy) | Out-Null
        $buttons.Children.Add($close) | Out-Null
        $panel.Children.Add($buttons) | Out-Null
        $window.Content = $panel
        $window.ShowDialog() | Out-Null
        $text.Text = ''
    })
    $sync.State.CreatedPasswords = @()
}

function Test-NetIPGraphConnection {
    [CmdletBinding()]
    param()

    if ($sync.App.Mock) { return $true }
    try {
        $context = Get-MgContext -ErrorAction Stop
        return ($null -ne $context -and -not [string]::IsNullOrWhiteSpace([string]$context.Account))
    }
    catch {
        return $false
    }
}

function Update-NetIPUIState {
    [CmdletBinding()]
    param()

    if (-not $sync.Form) { return }
    if (-not $sync.Form.Dispatcher.CheckAccess()) {
        $sync.Form.Dispatcher.Invoke([System.Action]{ Update-NetIPUIState })
        return
    }

    $domain = [string]$sync.State.OnMicrosoftDomain
    if ($sync.WPFDomain) { $sync.WPFDomain.Text = $domain }
    if ($sync.WPFUpnPreview1 -and $domain) { $sync.WPFUpnPreview1.Text = "$(if($sync.WPFUserPrefix1){$sync.WPFUserPrefix1.Text})@$domain" }
    if ($sync.WPFUpnPreview2 -and $domain) { $sync.WPFUpnPreview2.Text = "$(if($sync.WPFUserPrefix2){$sync.WPFUserPrefix2.Text})@$domain" }
    if ($sync.WPFGraphStatus) {
        $sync.WPFGraphStatus.Text = if ($sync.State.GraphConnected) {
            if ($sync.State.Language -eq 'en-US') { 'Yes' } else { 'Ja' }
        }
        else {
            if ($sync.State.Language -eq 'en-US') { 'No' } else { 'Nej' }
        }
    }
    if ($sync.WPFGraphAccount) { $sync.WPFGraphAccount.Text = [string]$sync.State.GraphAccount }
    if ($sync.WPFTenantId) { $sync.WPFTenantId.Text = [string]$sync.State.TenantId }
    if ($sync.WPFTenantName) { $sync.WPFTenantName.Text = [string]$sync.State.TenantDisplayName }
    if ($sync.WPFOnMicrosoftDomain) { $sync.WPFOnMicrosoftDomain.Text = [string]$sync.State.OnMicrosoftDomain }
    if ($sync.WPFOutputFolder) { $sync.WPFOutputFolder.Text = [string]$sync.State.OutputFolder }
    if ($sync.WPFHandoffPath) { $sync.WPFHandoffPath.Text = [string]$sync.State.HandoffPath }
    $risk = [bool]$sync.WPFWelcomeRiskAccepted.IsChecked
    $hasGraph = [bool]$sync.State.GraphConnected
    $hasDiscovery = $null -ne $sync.State.Discovery
    $hasVisitedConfig = [bool]$sync.UI.ConfigVisited
    $hasPlan = $null -ne $sync.State.Plan
    $hasHandoff = -not [string]::IsNullOrWhiteSpace([string]$sync.State.HandoffPath)

    $sync.WPFStepWelcome.IsEnabled = $true
    $sync.WPFStepConnect.IsEnabled = $risk
    $sync.WPFStepDiscovery.IsEnabled = $risk -and $hasGraph
    $sync.WPFStepConfig.IsEnabled = $risk -and $hasGraph -and $hasDiscovery
    $sync.WPFStepPlan.IsEnabled = $risk -and $hasGraph -and $hasDiscovery -and $hasVisitedConfig
    $sync.WPFStepApply.IsEnabled = $risk -and $hasGraph -and $hasPlan
    $sync.WPFStepHandoff.IsEnabled = $risk -and $hasHandoff
}

function Write-NetIPLog {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string] $Message,
        [ValidateSet('INFO','WARN','ERROR','PASS','PLAN','DELETE')]
        [string] $Level = 'INFO'
    )

    $safeMessage = ConvertTo-NetIPRedactedError -ErrorRecord $Message
    $line = '[{0}] [{1}] {2}' -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'), $Level, $safeMessage
    $logFile = Get-NetIPObjectPropertyValue -InputObject $sync.Paths -Name 'LogFile'
    if ($logFile) {
        Add-Content -LiteralPath $logFile -Value $line -Encoding UTF8
    }
    if ($sync.WPFExecutionLog) {
        $appendLog = {
            $sync.WPFExecutionLog.AppendText($message + [Environment]::NewLine)
            $sync.WPFExecutionLog.ScrollToEnd()
        }
        $message = $line
        if ($sync.WPFExecutionLog.Dispatcher.CheckAccess()) {
            & $appendLog
        }
        else {
            $sync.WPFExecutionLog.Dispatcher.Invoke([System.Action]$appendLog)
        }
    }
}

function Write-NetIPStatus {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string] $Message,
        [switch] $Busy
    )

    Write-NetIPLog -Message $Message
    if ($sync.WPFStatusText) {
        $statusMessage = $Message
        $isBusy = [bool] $Busy
        $updateStatus = {
            $sync.WPFStatusText.Text = $statusMessage
            $sync.WPFProgressBar.IsIndeterminate = $isBusy
        }
        if ($sync.WPFStatusText.Dispatcher.CheckAccess()) {
            & $updateStatus
        }
        else {
            $sync.WPFStatusText.Dispatcher.Invoke([System.Action]$updateStatus)
        }
    }
}

function Initialize-NetIPWPFUI {
    [CmdletBinding()]
    param()

    $settings = $sync.configs.appsettings
    $defaults = $sync.configs.defaults
    $scopes = @($sync.configs.graphScopes)
    if ($settings) {
        $sync.App.Name = [string]$settings.name
        $sync.App.Version = [string]$settings.version
    }
    $sync.Form.Title = "$($sync.App.Name) v$($sync.App.Version)"
    $sync.WPFVersionBadge.Text = "v$($sync.App.Version)"
    $sync.WPFGraphScopes.Text = ($scopes -join [Environment]::NewLine)
    $sync.WPFDisplayName1.Text = [string]$defaults.account1DisplayName
    $sync.WPFUserPrefix1.Text = [string]$defaults.account1Prefix
    $sync.WPFDisplayName2.Text = [string]$defaults.account2DisplayName
    $sync.WPFUserPrefix2.Text = [string]$defaults.account2Prefix
    $sync.WPFGroupName.Text = [string]$settings.groupName
    $sync.WPFGroupDescription.Text = [string]$settings.groupDescription
    $sync.WPFCreateUsers.IsChecked = [bool]$defaults.createUsers
    $sync.WPFCreateGroup.IsChecked = [bool]$defaults.createGroup
    $sync.WPFAddUsersToGroup.IsChecked = [bool]$defaults.addUsersToGroup
    $sync.WPFPatchCAPolicies.IsChecked = [bool]$defaults.patchCAPolicies
    if ($sync.WPFLanguageSelector) { $sync.WPFLanguageSelector.SelectedIndex = 0 }
    Set-NetIPLanguage -Language $sync.State.Language

    if ($sync.App.Mock) {
        $sync.State.GraphConnected = $true
        $sync.State.GraphAccount = 'mock.consultant@contoso.onmicrosoft.com'
        Get-NetIPTenantInfo | Out-Null
        Write-NetIPStatus -Message 'Mock mode er aktiv. Der kaldes ikke Microsoft Graph.'
    }
    else {
        Write-NetIPStatus -Message 'Klar'
    }
    Invoke-NetIPWPFButton -Name 'WPFStepWelcome'
    Update-NetIPUIState
}

function Invoke-NetIPApplyConfiguration {
    [CmdletBinding()]
    param()

    if (-not $sync.State.Plan) {
        [System.Windows.MessageBox]::Show('Generér en plan før du udfører ændringer.', $sync.App.Name, 'OK', 'Warning') | Out-Null
        return
    }
    $config = Get-NetIPConfigFromUI
    $plan = $sync.State.Plan
    $summary = @"
Følgende udføres:

Brugere:
- $($plan.Account1UPN): $($plan.Account1Status)
- $($plan.Account2UPN): $($plan.Account2Status)

Eksisterende passwords ændres ikke.
Gruppe: $($plan.GroupName) / $($plan.GroupStatus)
Medlemskab opdateres: $($plan.AddAccountsToGroup)
Global Administrator tildeles direkte til begge konti: Ja
Conditional Access policies patches: $($plan.PatchConditionalAccess)
Antal policies der patches: $(@($plan.CAPoliciesToChange).Count)

CA policies bliver backuppet før patching.
Genererede passwords vises én gang og gemmes ikke.

Vil du fortsætte?
"@
    $answer = [System.Windows.MessageBox]::Show($summary, $sync.App.Name, 'YesNo', 'Warning')
    if ($answer -ne 'Yes') { return }

    Invoke-NetIPRunspace -ArgumentList @($config) -ScriptBlock {
        param($config)
        Write-NetIPStatus -Busy -Message 'Anvender konfiguration...'
        $tenant = Get-NetIPTenantInfo
        $output = if ($sync.State.OutputFolder) { $sync.State.OutputFolder } else { New-NetIPOutputFolder -TenantId $tenant.TenantId }
        New-Item -ItemType Directory -Force -Path $output | Out-Null

        $upn1 = ConvertTo-BreakGlassUpn -Prefix $config.UserPrefix1 -OnMicrosoftDomain $tenant.OnMicrosoftDomain
        $upn2 = ConvertTo-BreakGlassUpn -Prefix $config.UserPrefix2 -OnMicrosoftDomain $tenant.OnMicrosoftDomain
        $group = Ensure-NetIPSecurityGroup -DisplayName $config.GroupName -Description $config.GroupDescription -CreateIfMissing ([bool]$config.CreateGroup) -Apply $true
        Write-NetIPLog -Level PASS -Message "Gruppe håndteret: $($config.GroupName)"

        $createdPasswords = @()
        $users = [System.Collections.Generic.List[object]]::new()
        foreach ($item in @(
            @{ DisplayName = $config.DisplayName1; Upn = $upn1 },
            @{ DisplayName = $config.DisplayName2; Upn = $upn2 }
        )) {
            $existing = Get-NetIPUserByUpn -UserPrincipalName $item.Upn
            if ($existing) {
                $existing | Add-Member -MemberType NoteProperty -Name EnsureStatus -Value 'AlreadyExists' -Force
                $users.Add($existing)
                Write-NetIPLog -Level PASS -Message "Bruger findes og genbruges: $($item.Upn)"
                continue
            }
            if (-not $config.CreateUsers) {
                $users.Add([pscustomobject]@{ id=''; displayName=$item.DisplayName; userPrincipalName=$item.Upn; EnsureStatus='SkippedMissing' })
                Write-NetIPLog -Level WARN -Message "Bruger mangler og oprettes ikke: $($item.Upn)"
                continue
            }
            $password = New-NetIPRandomPassword
            $user = New-BreakGlassUser -DisplayName $item.DisplayName -UserPrincipalName $item.Upn -Password $password
            $users.Add($user)
            $createdPasswords += [pscustomobject]@{ UserPrincipalName = $item.Upn; Password = $password }
            Write-NetIPLog -Level PASS -Message "Bruger oprettet: $($item.Upn)"
        }

        $membership = @()
        if ($config.AddUsersToGroup) {
            foreach ($user in $users | Where-Object { Get-NetIPObjectPropertyValue -InputObject $_ -Name 'id' }) {
                $membership += Ensure-NetIPGroupMember -Group $group -User $user -Apply $true
            }
        }
        else {
            $membership += [pscustomobject]@{ Status='Skipped'; Detail='Gruppemedlemskab er fravalgt.' }
        }

        $roleDefinition = Get-NetIPGlobalAdministratorRoleDefinition
        $roleAssignments = @()
        foreach ($user in $users | Where-Object { Get-NetIPObjectPropertyValue -InputObject $_ -Name 'id' }) {
            $roleAssignments += Ensure-NetIPGlobalAdministratorAssignment -User $user -RoleDefinition $roleDefinition -Apply $true
        }

        $policies = @(Get-NetIPConditionalAccessPolicies)
        $backupPath = ''
        $caResults = @()
        $alreadyExcluded = @()
        $groupId = [string](Get-NetIPObjectPropertyValue -InputObject $group -Name 'id')
        $groupDisplayName = [string](Get-NetIPObjectPropertyValue -InputObject $group -Name 'displayName')
        $groupStatus = [string](Get-NetIPObjectPropertyValue -InputObject $group -Name 'EnsureStatus')
        if ($group -and $groupId) {
            foreach ($policy in $policies) {
                $excludeGroups = @(Get-NetIPObjectPropertyValue -InputObject (Get-NetIPObjectPropertyValue -InputObject (Get-NetIPObjectPropertyValue -InputObject $policy -Name 'conditions') -Name 'users') -Name 'excludeGroups')
                if ($excludeGroups -contains $groupId) {
                    $alreadyExcluded += [pscustomobject]@{
                        Policy = [string](Get-NetIPObjectPropertyValue -InputObject $policy -Name 'displayName')
                        PolicyId = [string](Get-NetIPObjectPropertyValue -InputObject $policy -Name 'id')
                        Status = 'AlreadyExcluded'
                    }
                }
            }
        }
        if ($config.PatchCAPolicies -and $group -and $groupId) {
            $backupPath = Backup-NetIPConditionalAccessPolicies -Policies $policies -OutputFolder $output
            $caResults = Add-NetIPGroupExclusionToCAPolicies -Policies $policies -GroupId $groupId -Apply $true
        }

        $changed = @($caResults | Where-Object Status -eq 'Patched')
        $failed = @($caResults | Where-Object Status -eq 'Failed')
        $account1Status = [string](Get-NetIPObjectPropertyValue -InputObject $users[0] -Name 'EnsureStatus')
        $account2Status = [string](Get-NetIPObjectPropertyValue -InputObject $users[1] -Name 'EnsureStatus')
        $result = [pscustomobject]@{
            TenantDisplayName = $tenant.TenantDisplayName
            TenantId = $tenant.TenantId
            Timestamp = (Get-Date).ToString('o')
            Operator = $sync.State.GraphAccount
            OnMicrosoftDomain = $tenant.OnMicrosoftDomain
            Account1 = [pscustomobject]@{ DisplayName=$config.DisplayName1; UserPrincipalName=$upn1; Status=$account1Status }
            Account2 = [pscustomobject]@{ DisplayName=$config.DisplayName2; UserPrincipalName=$upn2; Status=$account2Status }
            Group = [pscustomobject]@{ DisplayName=$groupDisplayName; Id=$groupId; Status=$groupStatus }
            GroupMembership = $membership
            RoleAssignments = $roleAssignments
            CAExclusionsEnabled = [bool]$config.PatchCAPolicies
            CAPoliciesChangedCount = $changed.Count
            CAPoliciesChanged = $changed
            CAPoliciesAlreadyExcluded = $alreadyExcluded
            CAPoliciesFailed = $failed
            CABackupPath = $backupPath
            Warnings = @($sync.State.Warnings)
        }
        $sync.State.Result = $result
        Save-NetIPResultJson -Result $result -OutputFolder $output | Out-Null
        $handoff = New-NetIPHandoffHtml -Result $result -OutputFolder $output
        $sync.State.HandoffPath = $handoff
        if ($createdPasswords.Count -gt 0) {
            $sync.State.CreatedPasswords = $createdPasswords
            Show-NetIPCreatedPasswordsOnce -CreatedPasswords $createdPasswords
        }
        $sync.Form.Dispatcher.Invoke([System.Action]{
            $sync.WPFOutputFolder.Text = $sync.State.OutputFolder
            $sync.WPFHandoffPath.Text = $sync.State.HandoffPath
            Invoke-NetIPWPFButton -Name 'WPFStepHandoff'
        })
        Write-NetIPStatus -Message 'Konfiguration er anvendt, og handoff er genereret.'
    }
}

function Invoke-NetIPBuildPlan {
    [CmdletBinding()]
    param()

    if (-not $sync.State.GraphConnected -and -not $sync.App.Mock) {
        [System.Windows.MessageBox]::Show('Du skal først forbinde til Microsoft Graph.', $sync.App.Name, 'OK', 'Warning') | Out-Null
        return
    }
    $config = Get-NetIPConfigFromUI
    Invoke-NetIPRunspace -ArgumentList @($config) -ScriptBlock {
        param($config)
        Write-NetIPStatus -Busy -Message 'Genererer plan...'
        $plan = New-NetIPPlanObject -Config $config -Discovery $sync.State.Discovery
        if (-not $sync.State.OutputFolder) {
            $sync.State.OutputFolder = New-NetIPOutputFolder -TenantId $plan.TenantId
        }
        $plan.OutputFolder = $sync.State.OutputFolder
        $plan.HandoffPath = Join-Path $sync.State.OutputFolder 'handoff.html'
        Export-NetIPJsonSafe -InputObject $plan -Path (Join-Path $sync.State.OutputFolder 'plan.json') -Depth 30 | Out-Null
        $text = @"
Tenant: $($plan.TenantDisplayName) / $($plan.TenantId)
Domain: $($plan.OnMicrosoftDomain)

Konto 1: $($plan.Account1DisplayName) / $($plan.Account1UPN) / $($plan.Account1Status)
Konto 2: $($plan.Account2DisplayName) / $($plan.Account2UPN) / $($plan.Account2Status)

Gruppe: $($plan.GroupName) / $($plan.GroupStatus)
Tilføj konti til gruppe: $($plan.AddAccountsToGroup)
Tildel Global Administrator: $($plan.AssignGlobalAdministrator) / scope $($plan.RoleAssignmentScope)

Conditional Access policies fundet: $($plan.ConditionalAccessCount)
Patch CA policies: $($plan.PatchConditionalAccess)
Policies der ændres: $(@($plan.CAPoliciesToChange).Count)
Policies der allerede ekskluderer gruppen: $(@($plan.CAPoliciesAlreadyExcluded).Count)

Output folder: $($plan.OutputFolder)
Handoff: $($plan.HandoffPath)

Advarsler:
$($plan.Warnings -join [Environment]::NewLine)

JSON:
$($plan | ConvertTo-Json -Depth 30)
"@
        $sync.Form.Dispatcher.Invoke([System.Action]{
            $sync.WPFPlanText.Text = $text
            Invoke-NetIPWPFButton -Name 'WPFStepPlan'
        })
        Write-NetIPStatus -Message 'Plan er genereret.'
    }
}

function Invoke-NetIPConnectTenant {
    [CmdletBinding()]
    param()

    Invoke-NetIPRunspace -ScriptBlock {
        if ($sync.App.Mock) {
            $sync.State.GraphConnected = $true
            $sync.State.GraphAccount = 'mock.consultant@contoso.onmicrosoft.com'
            Get-NetIPTenantInfo | Out-Null
            Write-NetIPStatus -Message 'Mock tenant er forbundet.'
            return
        }

        Write-NetIPStatus -Busy -Message 'Forbinder til Microsoft Graph...'
        $module = Get-Module -ListAvailable -Name Microsoft.Graph.Authentication | Select-Object -First 1
        if (-not $module) {
            $install = $sync.Form.Dispatcher.Invoke([func[object]]{
                [System.Windows.MessageBox]::Show('Microsoft.Graph.Authentication mangler. Vil du installere modulet for CurrentUser fra PSGallery?', $sync.App.Name, 'YesNo', 'Question')
            })
            if ($install -ne 'Yes') {
                throw 'Microsoft Graph modulet mangler, og installation blev ikke godkendt.'
            }
            Install-Module -Name Microsoft.Graph.Authentication -Scope CurrentUser -Repository PSGallery -Force -AllowClobber -ErrorAction Stop
        }
        Import-Module Microsoft.Graph.Authentication -ErrorAction Stop
        $scopes = @($sync.configs.graphScopes)
        Connect-MgGraph -Scopes $scopes -ContextScope Process -NoWelcome -ErrorAction Stop | Out-Null
        $context = Get-MgContext
        $sync.State.GraphConnected = $true
        $sync.State.GraphAccount = [string]$context.Account
        $sync.State.GraphScopes = @($context.Scopes)
        Get-NetIPTenantInfo | Out-Null
        Write-NetIPStatus -Message 'Microsoft Graph er forbundet.'
    }
}

function Invoke-NetIPDiscovery {
    [CmdletBinding()]
    param()

    if (-not $sync.State.GraphConnected -and -not $sync.App.Mock) {
        [System.Windows.MessageBox]::Show("Du skal først forbinde til Microsoft Graph under trinnet 'Forbind'.", $sync.App.Name, 'OK', 'Warning') | Out-Null
        return
    }
    $config = Get-NetIPConfigFromUI
    Invoke-NetIPRunspace -ArgumentList @($config) -ScriptBlock {
        param($config)
        Write-NetIPStatus -Busy -Message 'Kører discovery...'
        $tenant = Get-NetIPTenantInfo
        $upn1 = ConvertTo-BreakGlassUpn -Prefix $config.UserPrefix1 -OnMicrosoftDomain $tenant.OnMicrosoftDomain
        $upn2 = ConvertTo-BreakGlassUpn -Prefix $config.UserPrefix2 -OnMicrosoftDomain $tenant.OnMicrosoftDomain
        $user1 = Get-NetIPUserByUpn -UserPrincipalName $upn1
        $user2 = Get-NetIPUserByUpn -UserPrincipalName $upn2
        $group = Get-NetIPGroupByDisplayName -DisplayName $config.GroupName
        $policies = @(Get-NetIPConditionalAccessPolicies)
        $already = @()
        $groupId = [string](Get-NetIPObjectPropertyValue -InputObject $group -Name 'id')
        if ($group -and $groupId) {
            foreach ($policy in $policies) {
                $excludeGroups = @(Get-NetIPObjectPropertyValue -InputObject (Get-NetIPObjectPropertyValue -InputObject (Get-NetIPObjectPropertyValue -InputObject $policy -Name 'conditions') -Name 'users') -Name 'excludeGroups')
                if ($excludeGroups -contains $groupId) { $already += $policy }
            }
        }
        $discovery = [pscustomobject]@{
            Tenant = $tenant
            User1 = $user1
            User2 = $user2
            Group = $group
            CAPolicies = $policies
            CAPoliciesAlreadyExcluded = $already
            TargetUPN1 = $upn1
            TargetUPN2 = $upn2
            Timestamp = (Get-Date).ToString('o')
        }
        $sync.State.Discovery = $discovery
        $summary = "User1: $(if($user1){'findes'}else{'mangler'}); User2: $(if($user2){'findes'}else{'mangler'}); Gruppe: $(if($group){'findes'}else{'mangler'}); CA policies: $($policies.Count)"
        $userMissingSeverity = if ($config.CreateUsers) { 'Warning' } else { 'Bad' }
        $groupMissingSeverity = if ($config.CreateGroup) { 'Warning' } else { 'Bad' }
        $excludedSeverity = if ($policies.Count -eq 0) {
            'Good'
        }
        elseif ($already.Count -eq $policies.Count) {
            'Good'
        }
        elseif ($config.PatchCAPolicies) {
            'Warning'
        }
        else {
            'Bad'
        }
        $summarySeverity = if ((-not $user1 -and -not $config.CreateUsers) -or (-not $user2 -and -not $config.CreateUsers) -or (-not $group -and -not $config.CreateGroup) -or $excludedSeverity -eq 'Bad') {
            'Bad'
        }
        elseif (-not $user1 -or -not $user2 -or -not $group -or $excludedSeverity -eq 'Warning') {
            'Warning'
        }
        else {
            'Good'
        }
        $lines = @(
            [pscustomobject]@{ Severity = 'Info'; Text = "Tenant: $($tenant.TenantDisplayName) / $($tenant.TenantId)" },
            [pscustomobject]@{ Severity = 'Info'; Text = "Domain: $($tenant.OnMicrosoftDomain)" },
            [pscustomobject]@{ Severity = if($user1){'Good'}else{$userMissingSeverity}; Text = "Target user 1: $upn1 - $(if($user1){'Findes'}elseif($config.CreateUsers){'Mangler - planlagt oprettet'}else{'Mangler - oprettelse er fravalgt'})" },
            [pscustomobject]@{ Severity = if($user2){'Good'}else{$userMissingSeverity}; Text = "Target user 2: $upn2 - $(if($user2){'Findes'}elseif($config.CreateUsers){'Mangler - planlagt oprettet'}else{'Mangler - oprettelse er fravalgt'})" },
            [pscustomobject]@{ Severity = if($group){'Good'}else{$groupMissingSeverity}; Text = "Group $($config.GroupName): $(if($group){'Findes'}elseif($config.CreateGroup){'Mangler - planlagt oprettet'}else{'Mangler - oprettelse er fravalgt'})" },
            [pscustomobject]@{ Severity = 'Info'; Text = "Conditional Access policies: $($policies.Count)" },
            [pscustomobject]@{ Severity = $excludedSeverity; Text = "Policies der allerede ekskluderer gruppen: $($already.Count) af $($policies.Count)" }
        )
        $sync.Form.Dispatcher.Invoke([System.Action]{
            $sync.WPFDiscoverySummary.Text = $summary
            $sync.WPFDiscoverySummary.Foreground = switch ($summarySeverity) {
                'Good' { [System.Windows.Media.Brushes]::ForestGreen }
                'Warning' { [System.Windows.Media.Brushes]::DarkOrange }
                'Bad' { [System.Windows.Media.Brushes]::Firebrick }
                default { [System.Windows.Media.Brushes]::Black }
            }
            $document = New-Object System.Windows.Documents.FlowDocument
            foreach ($line in $lines) {
                $paragraph = New-Object System.Windows.Documents.Paragraph
                $prefix = switch ($line.Severity) {
                    'Good' { '[OK] ' }
                    'Warning' { '[ADVARSEL] ' }
                    'Bad' { '[FEJL] ' }
                    default { '[INFO] ' }
                }
                $run = New-Object System.Windows.Documents.Run ($prefix + $line.Text)
                $run.Foreground = switch ($line.Severity) {
                    'Good' { [System.Windows.Media.Brushes]::ForestGreen }
                    'Warning' { [System.Windows.Media.Brushes]::DarkOrange }
                    'Bad' { [System.Windows.Media.Brushes]::Firebrick }
                    default { [System.Windows.Media.Brushes]::SlateGray }
                }
                $run.FontWeight = if ($line.Severity -eq 'Info') { [System.Windows.FontWeights]::Normal } else { [System.Windows.FontWeights]::SemiBold }
                [void]$paragraph.Inlines.Add($run)
                [void]$document.Blocks.Add($paragraph)
            }
            $sync.WPFDiscoveryList.Document = $document
            Invoke-NetIPWPFButton -Name 'WPFStepDiscovery'
        })
        Write-NetIPStatus -Message 'Discovery er færdig.'
    }
}

function Invoke-NetIPOpenOutputFolder {
    [CmdletBinding()]
    param()

    if ($sync.State.OutputFolder -and (Test-Path -LiteralPath $sync.State.OutputFolder)) {
        Start-Process $sync.State.OutputFolder
    }
    else {
        [System.Windows.MessageBox]::Show('Outputmappen findes ikke endnu.', $sync.App.Name, 'OK', 'Information') | Out-Null
    }
}

function Invoke-NetIPOpenHandoff {
    [CmdletBinding()]
    param()

    if ($sync.State.HandoffPath -and (Test-Path -LiteralPath $sync.State.HandoffPath)) {
        Start-Process $sync.State.HandoffPath
    }
    else {
        [System.Windows.MessageBox]::Show('Handoff-dokumentet er ikke genereret endnu.', $sync.App.Name, 'OK', 'Information') | Out-Null
    }
}

function Invoke-NetIPWPFButton {
    [CmdletBinding()]
    param([Parameter(Mandatory)][string] $Name)

    switch ($Name) {
        'WPFStepWelcome' { Set-NetIPWPFStep -Step 'Welcome' }
        'WPFStepConnect' { Set-NetIPWPFStep -Step 'Connect' }
        'WPFStepDiscovery' { Set-NetIPWPFStep -Step 'Discovery' }
        'WPFStepConfig' { Set-NetIPWPFStep -Step 'Config' }
        'WPFStepPlan' { Set-NetIPWPFStep -Step 'Plan' }
        'WPFStepApply' { Set-NetIPWPFStep -Step 'Apply' }
        'WPFStepHandoff' { Set-NetIPWPFStep -Step 'Handoff' }
        'WPFConnectTenant' { Invoke-NetIPConnectTenant }
        'WPFRunDiscovery' { Invoke-NetIPDiscovery }
        'WPFBuildPlan' { Invoke-NetIPBuildPlan }
        'WPFApplyConfiguration' { Invoke-NetIPApplyConfiguration }
        'WPFOpenOutputFolder' { Invoke-NetIPOpenOutputFolder }
        'WPFOpenHandoff' { Invoke-NetIPOpenHandoff }
        default { Write-NetIPLog -Level WARN -Message "Ukendt UI handling: $Name" }
    }
}

function Set-NetIPWPFStep {
    [CmdletBinding()]
    param([Parameter(Mandatory)][string] $Step)

    if ($Step -eq 'Config') {
        $sync.UI.ConfigVisited = $true
    }

    foreach ($page in @('WPFPageWelcome','WPFPageConnect','WPFPageDiscovery','WPFPageConfig','WPFPagePlan','WPFPageApply','WPFPageHandoff')) {
        $sync[$page].Visibility = 'Collapsed'
    }
    $target = switch ($Step) {
        'Welcome' { 'WPFPageWelcome' }
        'Connect' { 'WPFPageConnect' }
        'Discovery' { 'WPFPageDiscovery' }
        'Config' { 'WPFPageConfig' }
        'Plan' { 'WPFPagePlan' }
        'Apply' { 'WPFPageApply' }
        'Handoff' { 'WPFPageHandoff' }
    }
    $sync[$target].Visibility = 'Visible'
    Update-NetIPUIState
}

$sync.configs.appsettings = @'
{
  "name": "Entra Break Glass Configurator",
  "version": "2.1.0",
  "outputRoot": ".\\Output",
  "groupName": "CA-BreakGlass-Exclude",
  "groupDescription": "Security group used to exclude dedicated break-glass accounts from existing Conditional Access policies."
}

'@ | ConvertFrom-Json
$sync.configs.defaults = @'
{
  "account1DisplayName": "BreakGlass 01",
  "account1Prefix": "BreakGlass01",
  "account2DisplayName": "BreakGlass 02",
  "account2Prefix": "BreakGlass02",
  "createUsers": true,
  "createGroup": true,
  "addUsersToGroup": true,
  "patchCAPolicies": false
}

'@ | ConvertFrom-Json
$sync.configs.graphScopes = @'
[
  "User.ReadWrite.All",
  "Group.ReadWrite.All",
  "Directory.Read.All",
  "Organization.Read.All",
  "RoleManagement.ReadWrite.Directory",
  "Policy.Read.All",
  "Policy.ReadWrite.ConditionalAccess"
]

'@ | ConvertFrom-Json
$inputXML = @'
<Window xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Title="Entra Break Glass Configurator"
        Width="1180" Height="760" MinWidth="980" MinHeight="650"
        WindowStartupLocation="CenterScreen"
        Background="#F8FAFC">
    <Window.Resources>
        <Style TargetType="Button">
            <Setter Property="MinHeight" Value="34"/>
            <Setter Property="Margin" Value="0,0,0,8"/>
            <Setter Property="Padding" Value="12,6"/>
        </Style>
        <Style TargetType="TextBox">
            <Setter Property="MinHeight" Value="28"/>
            <Setter Property="Margin" Value="0,2,0,8"/>
        </Style>
        <Style TargetType="CheckBox">
            <Setter Property="Margin" Value="0,4,0,8"/>
        </Style>
        <Style TargetType="TextBlock">
            <Setter Property="TextWrapping" Value="Wrap"/>
        </Style>
    </Window.Resources>
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto"/>
            <RowDefinition Height="*"/>
            <RowDefinition Height="Auto"/>
        </Grid.RowDefinitions>

        <Border Grid.Row="0" Background="#111827" Padding="18,14">
            <Grid>
                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="*"/>
                    <ColumnDefinition Width="Auto"/>
                </Grid.ColumnDefinitions>
                <StackPanel>
                    <TextBlock x:Name="WPFAppTitle" Text="Entra Break Glass Configurator" Foreground="White" FontSize="24" FontWeight="SemiBold"/>
                    <TextBlock x:Name="WPFAppSubtitle" Text="Simpel Microsoft Graph-baseret opsætning af break-glass konti og CA-exclude gruppe." Foreground="#CBD5E1" Margin="0,4,0,0"/>
                </StackPanel>
                <Border Grid.Column="1" BorderBrush="#64748B" BorderThickness="1" Background="#1F2937" CornerRadius="4" Padding="10,5" VerticalAlignment="Top">
                    <TextBlock x:Name="WPFVersionBadge" Foreground="#E5E7EB" FontWeight="SemiBold"/>
                </Border>
            </Grid>
        </Border>

        <Grid Grid.Row="1">
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="230"/>
                <ColumnDefinition Width="*"/>
            </Grid.ColumnDefinitions>
            <Border Grid.Column="0" Background="#E5E7EB" BorderBrush="#CBD5E1" BorderThickness="0,0,1,0" Padding="14">
                <StackPanel>
                    <Button x:Name="WPFStepWelcome" Content="1. Velkommen"/>
                    <Button x:Name="WPFStepConnect" Content="2. Forbind" IsEnabled="False"/>
                    <Button x:Name="WPFStepDiscovery" Content="3. Discovery" IsEnabled="False"/>
                    <Button x:Name="WPFStepConfig" Content="4. Konfiguration" IsEnabled="False"/>
                    <Button x:Name="WPFStepPlan" Content="5. Plan" IsEnabled="False"/>
                    <Button x:Name="WPFStepApply" Content="6. Udfør" IsEnabled="False"/>
                    <Button x:Name="WPFStepHandoff" Content="7. Handoff" IsEnabled="False"/>
                </StackPanel>
            </Border>

            <Grid Grid.Column="1" Margin="18">
                <Grid x:Name="WPFPageWelcome">
                    <ScrollViewer VerticalScrollBarVisibility="Auto">
                        <StackPanel MaxWidth="900">
                            <StackPanel Orientation="Horizontal" HorizontalAlignment="Right" Margin="0,0,0,12">
                                <TextBlock x:Name="WPFLanguageLabel" Text="Sprog" VerticalAlignment="Center" Margin="0,0,8,0"/>
                                <ComboBox x:Name="WPFLanguageSelector" Width="150" SelectedIndex="0">
                                    <ComboBoxItem Content="Dansk" Tag="da-DK"/>
                                    <ComboBoxItem Content="English" Tag="en-US"/>
                                </ComboBox>
                            </StackPanel>
                            <TextBlock Text="Velkommen" FontSize="22" FontWeight="SemiBold" Margin="0,0,0,12"/>
                            <TextBlock Text="Dette værktøj opretter to break-glass konti på tenantens .onmicrosoft.com domæne, opretter gruppen CA-BreakGlass-Exclude og kan valgfrit ekskludere gruppen fra eksisterende Conditional Access-politikker."/>
                            <TextBlock Margin="0,12,0,0" Text="Værktøjet forbinder kun til Microsoft Graph. Det bruger ikke Azure, PIM, RMAU, FIDO2, Log Analytics eller Sentinel."/>
                            <TextBlock Margin="0,12,0,0" Text="Discovery og Plan foretager ingen ændringer. Ændringer udføres først i trinnet Udfør."/>
                            <TextBlock Margin="0,12,0,0" Text="Midlertidige adgangskoder vises kun én gang og gemmes ikke i log, JSON eller handoff dokument."/>
                            <CheckBox x:Name="WPFWelcomeRiskAccepted" Margin="0,24,0,0" Content="Jeg forstår at dette script ændrer sikkerhedskritisk tenant-konfiguration."/>
                        </StackPanel>
                    </ScrollViewer>
                </Grid>

                <Grid x:Name="WPFPageConnect" Visibility="Collapsed">
                    <ScrollViewer VerticalScrollBarVisibility="Auto">
                        <StackPanel MaxWidth="900">
                            <TextBlock Text="Forbind" FontSize="22" FontWeight="SemiBold" Margin="0,0,0,12"/>
                            <TextBlock Text="Forbind én gang til Microsoft Graph. Samme session bruges til discovery, plan og udførsel."/>
                            <TextBlock Text="Requested Graph scopes:" FontWeight="SemiBold" Margin="0,16,0,4"/>
                            <TextBox x:Name="WPFGraphScopes" IsReadOnly="True" AcceptsReturn="True" Height="100" FontFamily="Consolas"/>
                            <Button x:Name="WPFConnectTenant" Content="Forbind til Microsoft 365 tenant" Width="240" HorizontalAlignment="Left"/>
                            <UniformGrid Columns="2" Margin="0,14,0,0">
                                <TextBlock Text="Forbundet:" FontWeight="SemiBold"/>
                                <TextBlock x:Name="WPFGraphStatus" Text="Nej"/>
                                <TextBlock Text="Konto:" FontWeight="SemiBold"/>
                                <TextBlock x:Name="WPFGraphAccount"/>
                                <TextBlock Text="Tenant ID:" FontWeight="SemiBold"/>
                                <TextBlock x:Name="WPFTenantId"/>
                                <TextBlock Text="Tenant navn:" FontWeight="SemiBold"/>
                                <TextBlock x:Name="WPFTenantName"/>
                                <TextBlock Text=".onmicrosoft.com domæne:" FontWeight="SemiBold"/>
                                <TextBlock x:Name="WPFOnMicrosoftDomain"/>
                            </UniformGrid>
                        </StackPanel>
                    </ScrollViewer>
                </Grid>

                <Grid x:Name="WPFPageDiscovery" Visibility="Collapsed">
                    <DockPanel>
                        <StackPanel DockPanel.Dock="Top">
                            <TextBlock Text="Discovery" FontSize="22" FontWeight="SemiBold" Margin="0,0,0,12"/>
                            <TextBlock Text="Discovery er read-only og kontrollerer kun de eksakte target UPNs, CA-BreakGlass-Exclude og eksisterende Conditional Access-politikker."/>
                            <Button x:Name="WPFRunDiscovery" Content="Kør discovery" Width="150" HorizontalAlignment="Left" Margin="0,14,0,8"/>
                            <TextBlock x:Name="WPFDiscoverySummary" FontWeight="SemiBold"/>
                        </StackPanel>
                        <RichTextBox x:Name="WPFDiscoveryList" IsReadOnly="True" VerticalScrollBarVisibility="Auto" HorizontalScrollBarVisibility="Auto" FontFamily="Consolas" BorderBrush="#CBD5E1" BorderThickness="1" Background="White"/>
                    </DockPanel>
                </Grid>

                <Grid x:Name="WPFPageConfig" Visibility="Collapsed">
                    <ScrollViewer VerticalScrollBarVisibility="Auto">
                        <Grid MaxWidth="920">
                            <Grid.ColumnDefinitions>
                                <ColumnDefinition Width="220"/>
                                <ColumnDefinition Width="*"/>
                                <ColumnDefinition Width="220"/>
                                <ColumnDefinition Width="*"/>
                            </Grid.ColumnDefinitions>
                            <Grid.RowDefinitions>
                                <RowDefinition Height="Auto"/><RowDefinition Height="Auto"/><RowDefinition Height="Auto"/>
                                <RowDefinition Height="Auto"/><RowDefinition Height="Auto"/><RowDefinition Height="Auto"/>
                                <RowDefinition Height="Auto"/><RowDefinition Height="Auto"/><RowDefinition Height="Auto"/>
                                <RowDefinition Height="Auto"/><RowDefinition Height="Auto"/>
                            </Grid.RowDefinitions>
                            <TextBlock Grid.Row="0" Grid.ColumnSpan="4" Text="Konfiguration" FontSize="22" FontWeight="SemiBold" Margin="0,0,0,12"/>
                            <TextBlock Grid.Row="1" Grid.Column="0" Text="Account 1 display name"/>
                            <TextBox x:Name="WPFDisplayName1" Grid.Row="1" Grid.Column="1" Margin="0,2,16,8"/>
                            <TextBlock Grid.Row="1" Grid.Column="2" Text="Account 1 UPN prefix"/>
                            <TextBox x:Name="WPFUserPrefix1" Grid.Row="1" Grid.Column="3"/>
                            <TextBlock Grid.Row="2" Grid.Column="0" Text="Account 2 display name"/>
                            <TextBox x:Name="WPFDisplayName2" Grid.Row="2" Grid.Column="1" Margin="0,2,16,8"/>
                            <TextBlock Grid.Row="2" Grid.Column="2" Text="Account 2 UPN prefix"/>
                            <TextBox x:Name="WPFUserPrefix2" Grid.Row="2" Grid.Column="3"/>
                            <TextBlock Grid.Row="3" Grid.Column="0" Text="Domain"/>
                            <TextBox x:Name="WPFDomain" Grid.Row="3" Grid.Column="1" Grid.ColumnSpan="3" IsReadOnly="True"/>
                            <TextBlock Grid.Row="4" Grid.Column="0" Text="Final UPN preview"/>
                            <StackPanel Grid.Row="4" Grid.Column="1" Grid.ColumnSpan="3">
                                <TextBlock x:Name="WPFUpnPreview1" FontFamily="Consolas"/>
                                <TextBlock x:Name="WPFUpnPreview2" FontFamily="Consolas"/>
                            </StackPanel>
                            <TextBlock Grid.Row="5" Grid.Column="0" Text="Security group name"/>
                            <TextBox x:Name="WPFGroupName" Grid.Row="5" Grid.Column="1" Grid.ColumnSpan="3" IsReadOnly="True"/>
                            <TextBlock Grid.Row="6" Grid.Column="0" Text="Security group description"/>
                            <TextBox x:Name="WPFGroupDescription" Grid.Row="6" Grid.Column="1" Grid.ColumnSpan="3" IsReadOnly="True" TextWrapping="Wrap" Height="58"/>
                            <StackPanel Grid.Row="7" Grid.Column="0" Grid.ColumnSpan="4" Margin="0,10,0,0">
                                <CheckBox x:Name="WPFCreateUsers" Content="Opret brugere hvis de ikke findes"/>
                                <CheckBox x:Name="WPFCreateGroup" Content="Opret gruppen CA-BreakGlass-Exclude hvis den ikke findes"/>
                                <CheckBox x:Name="WPFAddUsersToGroup" Content="Tilføj break-glass konti til CA-BreakGlass-Exclude"/>
                                <CheckBox x:Name="WPFPatchCAPolicies" Content="Ekskludér CA-BreakGlass-Exclude fra alle eksisterende Conditional Access-politikker"/>
                                <TextBlock Foreground="#92400E" Text="Dette ændrer eksisterende Conditional Access-politikker. Der oprettes backup før ændringerne udføres."/>
                            </StackPanel>
                        </Grid>
                    </ScrollViewer>
                </Grid>

                <Grid x:Name="WPFPagePlan" Visibility="Collapsed">
                    <DockPanel>
                        <StackPanel DockPanel.Dock="Top">
                            <TextBlock Text="Plan" FontSize="22" FontWeight="SemiBold" Margin="0,0,0,12"/>
                            <Button x:Name="WPFBuildPlan" Content="Generér plan" Width="150" HorizontalAlignment="Left"/>
                        </StackPanel>
                        <TextBox x:Name="WPFPlanText" IsReadOnly="True" AcceptsReturn="True" VerticalScrollBarVisibility="Auto" HorizontalScrollBarVisibility="Auto" FontFamily="Consolas"/>
                    </DockPanel>
                </Grid>

                <Grid x:Name="WPFPageApply" Visibility="Collapsed">
                    <DockPanel>
                        <StackPanel DockPanel.Dock="Top">
                            <TextBlock Text="Udfør" FontSize="22" FontWeight="SemiBold" Margin="0,0,0,12"/>
                            <TextBlock Text="Dette er det eneste trin der ændrer tenant-konfiguration."/>
                            <Button x:Name="WPFApplyConfiguration" Content="Anvend konfiguration" Width="180" HorizontalAlignment="Left" Margin="0,14,0,8"/>
                        </StackPanel>
                        <TextBox x:Name="WPFExecutionLog" IsReadOnly="True" AcceptsReturn="True" VerticalScrollBarVisibility="Auto" HorizontalScrollBarVisibility="Auto" FontFamily="Consolas"/>
                    </DockPanel>
                </Grid>

                <Grid x:Name="WPFPageHandoff" Visibility="Collapsed">
                    <StackPanel MaxWidth="900">
                        <TextBlock Text="Handoff" FontSize="22" FontWeight="SemiBold" Margin="0,0,0,12"/>
                        <TextBlock Text="Handoff-dokumentet genereres efter udførsel. Det indeholder ikke passwords."/>
                        <TextBlock Text="Output folder" FontWeight="SemiBold" Margin="0,18,0,4"/>
                        <TextBox x:Name="WPFOutputFolder" IsReadOnly="True"/>
                        <TextBlock Text="Handoff dokument" FontWeight="SemiBold" Margin="0,10,0,4"/>
                        <TextBox x:Name="WPFHandoffPath" IsReadOnly="True"/>
                        <StackPanel Orientation="Horizontal" Margin="0,12,0,0">
                            <Button x:Name="WPFOpenOutputFolder" Content="Åbn outputmappe" Width="150" Margin="0,0,8,0"/>
                            <Button x:Name="WPFOpenHandoff" Content="Åbn handoff" Width="130"/>
                        </StackPanel>
                    </StackPanel>
                </Grid>
            </Grid>
        </Grid>

        <Border Grid.Row="2" Background="#F1F5F9" BorderBrush="#CBD5E1" BorderThickness="0,1,0,0" Padding="12,8">
            <Grid>
                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="*"/>
                    <ColumnDefinition Width="220"/>
                </Grid.ColumnDefinitions>
                <TextBlock x:Name="WPFStatusText" Text="Klar"/>
                <ProgressBar x:Name="WPFProgressBar" Grid.Column="1" Height="14" IsIndeterminate="False"/>
            </Grid>
        </Border>
    </Grid>
</Window>

'@
$maxThreads = 1
$initialSessionState = [System.Management.Automation.Runspaces.InitialSessionState]::CreateDefault()
$initialSessionState.Variables.Add((New-Object System.Management.Automation.Runspaces.SessionStateVariableEntry -ArgumentList 'sync', $sync, $null))
$initialSessionState.Variables.Add((New-Object System.Management.Automation.Runspaces.SessionStateVariableEntry -ArgumentList 'DebugPreference', $DebugPreference, $null))

Get-ChildItem function:\ | Where-Object { $_.Name -like '*-NetIP*' -or $_.Name -like '*-BreakGlass*' } | ForEach-Object {
    $definition = Get-Content function:\$($_.Name)
    $initialSessionState.Commands.Add((New-Object System.Management.Automation.Runspaces.SessionStateFunctionEntry -ArgumentList $_.Name, $definition))
}

$sync.Runspace = [runspacefactory]::CreateRunspacePool(1, $maxThreads, $initialSessionState, $Host)
$sync.Runspace.ApartmentState = 'STA'
$sync.Runspace.ThreadOptions = 'ReuseThread'
$sync.Runspace.Open()

$inputXML = $inputXML -replace 'mc:Ignorable="d"', '' -replace 'x:Name', 'Name'
[xml]$xaml = $inputXML
$reader = New-Object System.Xml.XmlNodeReader $xaml
$sync.Form = [Windows.Markup.XamlReader]::Load($reader)

$xaml.SelectNodes("//*[@Name]") | ForEach-Object {
    $sync[$_.Name] = $sync.Form.FindName($_.Name)
}

Initialize-NetIPWPFUI

$sync.Keys | ForEach-Object {
    $control = $sync[$_]
    if ($control -and $control.GetType().Name -eq 'Button' -and $_ -like 'WPF*') {
        $control.Add_Click({
            param($sender, $eventArgs)
            Invoke-NetIPWPFButton -Name $sender.Name
        })
    }
}

foreach ($box in @('WPFDisplayName1','WPFUserPrefix1','WPFDisplayName2','WPFUserPrefix2')) {
    if ($sync[$box]) {
        $sync[$box].Add_TextChanged({ Update-NetIPUIState })
    }
}

$sync.WPFWelcomeRiskAccepted.Add_Checked({ Update-NetIPUIState })
$sync.WPFWelcomeRiskAccepted.Add_Unchecked({ Update-NetIPUIState })
if ($sync.WPFLanguageSelector) {
    $sync.WPFLanguageSelector.Add_SelectionChanged({
        $selected = $sync.WPFLanguageSelector.SelectedItem
        $language = if ($selected -and $selected.Tag) { [string]$selected.Tag } else { 'da-DK' }
        Set-NetIPLanguage -Language $language
        Update-NetIPUIState
    })
}

$sync.Form.Add_Closing({
    if ($sync.Runspace) {
        $sync.Runspace.Close()
        $sync.Runspace.Dispose()
    }
})

$sync.Form.ShowDialog() | Out-Null

