param(
    [switch] $Run,
    [switch] $Mock
)

$ErrorActionPreference = 'Stop'
$scriptName = 'NetIPBreakGlass.ps1'
$root = $PSScriptRoot
$outputPath = Join-Path -Path $root -ChildPath $scriptName

$sync = [Hashtable]::Synchronized(@{})
$sync.configs = @{}
$parts = [System.Collections.Generic.List[string]]::new()

$warning = @"
# ==================================================================================================
# This file is generated by Compile.ps1. Do not edit directly.
# Source of truth: scripts/, functions/, config/ and xaml/ in the NetIP-BreakGlass source tree.
# ==================================================================================================
"@
$parts.Add($warning)

$parts.Add((Get-Content -LiteralPath (Join-Path $root 'scripts\start.ps1') -Raw -Encoding UTF8))

Get-ChildItem -LiteralPath (Join-Path $root 'functions') -Recurse -File -Filter '*.ps1' |
    Sort-Object FullName |
    ForEach-Object {
        $parts.Add((Get-Content -LiteralPath $_.FullName -Raw -Encoding UTF8))
    }

Get-ChildItem -LiteralPath (Join-Path $root 'config') -File -Filter '*.json' |
    Sort-Object Name |
    ForEach-Object {
        $json = Get-Content -LiteralPath $_.FullName -Raw -Encoding UTF8
        $null = $json | ConvertFrom-Json
        $name = $_.BaseName
        $parts.Add(@"
`$sync.configs.$name = @'
$json
'@ | ConvertFrom-Json
"@)
    }

$xaml = Get-Content -LiteralPath (Join-Path $root 'xaml\inputXML.xaml') -Raw -Encoding UTF8
[xml]$null = $xaml
$parts.Add(@"
`$inputXML = @'
$xaml
'@
"@)

$parts.Add((Get-Content -LiteralPath (Join-Path $root 'scripts\main.ps1') -Raw -Encoding UTF8))

Set-Content -LiteralPath $outputPath -Value ($parts -join "`r`n") -Encoding UTF8

$tokens = $null
$errors = $null
[System.Management.Automation.Language.Parser]::ParseFile($outputPath, [ref]$tokens, [ref]$errors) | Out-Null
if ($errors) {
    $errors | Format-List *
    throw "Syntax validation failed for $scriptName"
}

Write-Host "Compiled $scriptName" -ForegroundColor Green

if ($Run) {
    $args = @('-NoProfile','-ExecutionPolicy','Bypass','-STA','-File',"`"$outputPath`"")
    if ($Mock) { $args += '-Mock' }
    & pwsh @args
}
